//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AgentState.
const (
	AgentStateIdle     AgentState = "idle"
	AgentStateRunning  AgentState = "running"
	AgentStateStopping AgentState = "stopping"
)

// Defines values for AgentOutputResponseType.
const (
	AgentOutputResponseTypeAgent      AgentOutputResponseType = "agent"
	AgentOutputResponseTypeStatus     AgentOutputResponseType = "status"
	AgentOutputResponseTypeTool       AgentOutputResponseType = "tool"
	AgentOutputResponseTypeToolResult AgentOutputResponseType = "tool_result"
	AgentOutputResponseTypeUsage      AgentOutputResponseType = "usage"
)

// Defines values for AgentSummaryState.
const (
	AgentSummaryStateIdle     AgentSummaryState = "idle"
	AgentSummaryStateRunning  AgentSummaryState = "running"
	AgentSummaryStateStopping AgentSummaryState = "stopping"
)

// Defines values for AgentUpdateState.
const (
	AgentUpdateStateIdle     AgentUpdateState = "idle"
	AgentUpdateStateRunning  AgentUpdateState = "running"
	AgentUpdateStateStopping AgentUpdateState = "stopping"
)

// Defines values for ErrorCode.
const (
	Conflict             ErrorCode = "conflict"
	CursorInvalid        ErrorCode = "cursor_invalid"
	Forbidden            ErrorCode = "forbidden"
	IdempotencyConflict  ErrorCode = "idempotency_conflict"
	Internal             ErrorCode = "internal"
	Invalid              ErrorCode = "invalid"
	InvalidLimit         ErrorCode = "invalid_limit"
	InvalidMessage       ErrorCode = "invalid_message"
	InvalidProject       ErrorCode = "invalid_project"
	InvalidSettings      ErrorCode = "invalid_settings"
	InvalidWorkspace     ErrorCode = "invalid_workspace"
	MethodNotAllowed     ErrorCode = "method_not_allowed"
	NotFound             ErrorCode = "not_found"
	NotPending           ErrorCode = "not_pending"
	NotRunning           ErrorCode = "not_running"
	ProjectExists        ErrorCode = "project_exists"
	ProjectNotEmpty      ErrorCode = "project_not_empty"
	Settled              ErrorCode = "settled"
	ShuttingDown         ErrorCode = "shutting_down"
	StorageFailed        ErrorCode = "storage_failed"
	TooLarge             ErrorCode = "too_large"
	TurnRequired         ErrorCode = "turn_required"
	UnsupportedMediaType ErrorCode = "unsupported_media_type"
	WorkspaceFailed      ErrorCode = "workspace_failed"
	WorkspaceLocked      ErrorCode = "workspace_locked"
	WorkspaceUnavailable ErrorCode = "workspace_unavailable"
)

// Defines values for EventType.
const (
	AgentCreated     EventType = "agent.created"
	AgentUpdated     EventType = "agent.updated"
	Conversation     EventType = "conversation"
	MessageCancelled EventType = "message.cancelled"
	MessageQueued    EventType = "message.queued"
	Output           EventType = "output"
	TurnCancelled    EventType = "turn.cancelled"
	TurnCompleted    EventType = "turn.completed"
	TurnFailed       EventType = "turn.failed"
	TurnInterrupted  EventType = "turn.interrupted"
	TurnStarted      EventType = "turn.started"
)

// Defines values for HealthApiVersion.
const (
	N1 HealthApiVersion = "1"
)

// Defines values for QueuedMessageStatus.
const (
	QueuedMessageStatusCancelled   QueuedMessageStatus = "cancelled"
	QueuedMessageStatusCompleted   QueuedMessageStatus = "completed"
	QueuedMessageStatusFailed      QueuedMessageStatus = "failed"
	QueuedMessageStatusInterrupted QueuedMessageStatus = "interrupted"
	QueuedMessageStatusPending     QueuedMessageStatus = "pending"
	QueuedMessageStatusRunning     QueuedMessageStatus = "running"
)

// Defines values for WSAckType.
const (
	Ack WSAckType = "ack"
)

// Defines values for WSErrorType.
const (
	WSErrorTypeError WSErrorType = "error"
)

// Defines values for WSEventType.
const (
	WSEventTypeEvent WSEventType = "event"
)

// Defines values for WSEventReferenceType.
const (
	EventRef WSEventReferenceType = "event_ref"
)

// Defines values for WSInventoryType.
const (
	Inventory WSInventoryType = "inventory"
)

// Defines values for WSSubmitType.
const (
	Submit WSSubmitType = "submit"
)

// Defines values for WSSubscribeType.
const (
	Subscribe WSSubscribeType = "subscribe"
)

// Defines values for WSSubscribedType.
const (
	Subscribed WSSubscribedType = "subscribed"
)

// Defines values for WorkspaceMode.
const (
	WorkspaceModeCurrentCheckout WorkspaceMode = "current_checkout"
	WorkspaceModeWorktree        WorkspaceMode = "worktree"
)

// Defines values for WorkspaceStatus.
const (
	Creating WorkspaceStatus = "creating"
	Draft    WorkspaceStatus = "draft"
	Failed   WorkspaceStatus = "failed"
	Fetching WorkspaceStatus = "fetching"
	Ready    WorkspaceStatus = "ready"
)

// Defines values for WorkspaceSelectionMode.
const (
	WorkspaceSelectionModeCurrentCheckout WorkspaceSelectionMode = "current_checkout"
	WorkspaceSelectionModeWorktree        WorkspaceSelectionMode = "worktree"
)

// Agent defines model for Agent.
type Agent struct {
	ActiveSettings     *Settings        `json:"active_settings,omitempty"`
	ContextUsage       *ContextUsage    `json:"context_usage,omitempty"`
	CreatedAt          time.Time        `json:"created_at"`
	Cursor             int64            `json:"cursor"`
	Held               bool             `json:"held"`
	Id                 string           `json:"id"`
	LastResponseCursor *int64           `json:"last_response_cursor,omitempty"`
	Messages           *[]Message       `json:"messages,omitempty"`
	ParentAgentId      *string          `json:"parent_agent_id,omitempty"`
	ProjectId          string           `json:"project_id"`
	Queue              *[]QueuedMessage `json:"queue,omitempty"`
	ReadCursor         *int64           `json:"read_cursor,omitempty"`
	Settings           Settings         `json:"settings"`
	Settled            bool             `json:"settled"`
	State              AgentState       `json:"state"`
	Title              string           `json:"title"`
	UpdatedAt          time.Time        `json:"updated_at"`
	Workspace          *Workspace       `json:"workspace,omitempty"`
}

// AgentState defines model for Agent.State.
type AgentState string

// AgentOutput Retained agent.AgentResponse. PascalCase field names are intentional compatibility with the existing runtime output payload.
type AgentOutput struct {
	// Content Display/provider-context output, possibly capped for tool results.
	Content string `json:"Content"`

	// FullToolOutput Complete uncapped tool stdout/stderr including cancellation/failure annotations; empty on non-tool-result output.
	FullToolOutput string                  `json:"FullToolOutput"`
	ResponseType   AgentOutputResponseType `json:"ResponseType"`
	ToolCallID     string                  `json:"ToolCallID"`
	ToolName       string                  `json:"ToolName"`
}

// AgentOutputResponseType defines model for AgentOutput.ResponseType.
type AgentOutputResponseType string

// AgentSummary defines model for AgentSummary.
type AgentSummary struct {
	ActiveSettings     *Settings         `json:"active_settings,omitempty"`
	ContextUsage       *ContextUsage     `json:"context_usage,omitempty"`
	CreatedAt          time.Time         `json:"created_at"`
	Cursor             int64             `json:"cursor"`
	Held               bool              `json:"held"`
	Id                 string            `json:"id"`
	LastResponseCursor *int64            `json:"last_response_cursor,omitempty"`
	ParentAgentId      *string           `json:"parent_agent_id,omitempty"`
	ProjectId          string            `json:"project_id"`
	ReadCursor         *int64            `json:"read_cursor,omitempty"`
	Settings           Settings          `json:"settings"`
	Settled            bool              `json:"settled"`
	State              AgentSummaryState `json:"state"`
	Title              string            `json:"title"`
	UpdatedAt          time.Time         `json:"updated_at"`
	Workspace          *Workspace        `json:"workspace,omitempty"`
}

// AgentSummaryState defines model for AgentSummary.State.
type AgentSummaryState string

// AgentUpdate State payload for agent.created and agent.updated. The enclosing Event supplies agent_id, cursor and created_at. This is not a complete Agent resource; it deliberately excludes history and queue.
type AgentUpdate struct {
	ActiveSettings     *NullableSettings `json:"active_settings"`
	ContextUsage       ContextUsage      `json:"context_usage"`
	Held               bool              `json:"held"`
	Id                 string            `json:"id"`
	LastResponseCursor *int64            `json:"last_response_cursor,omitempty"`
	ParentAgentId      *string           `json:"parent_agent_id,omitempty"`
	ProjectId          string            `json:"project_id"`
	ReadCursor         *int64            `json:"read_cursor,omitempty"`
	Settings           Settings          `json:"settings"`
	Settled            bool              `json:"settled"`
	State              AgentUpdateState  `json:"state"`
	Title              string            `json:"title"`
	Workspace          *Workspace        `json:"workspace,omitempty"`
}

// AgentUpdateState defines model for AgentUpdate.State.
type AgentUpdateState string

// ContentPart defines model for ContentPart.
type ContentPart struct {
	ImageUrl             *ContentPart_ImageUrl  `json:"image_url,omitempty"`
	Text                 *string                `json:"text,omitempty"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContentPartImageUrl1 defines model for .
type ContentPartImageUrl1 = string

// ContentPart_ImageUrl defines model for ContentPart.ImageUrl.
type ContentPart_ImageUrl struct {
	union json.RawMessage
}

// ContextUsage defines model for ContextUsage.
type ContextUsage struct {
	ContextWindow   int64  `json:"context_window"`
	Estimated       bool   `json:"estimated"`
	EstimatedTokens int64  `json:"estimated_tokens"`
	InputTokens     int64  `json:"input_tokens"`
	Known           bool   `json:"known"`
	Model           string `json:"model"`
	OutputTokens    int64  `json:"output_tokens"`
}

// ConversationDelta New committed messages appended since the previous conversation event, not a full conversation snapshot.
type ConversationDelta = []Message

// CreateAgentRequest Creates an idle agent unless prompt is supplied. Optional parent_agent_id must identify an existing agent on this server and is immutable after creation. Omitted directory and workspace overrides share an established parent worktree in the same project; otherwise project defaults apply.
type CreateAgentRequest struct {
	ParentAgentId *string        `json:"parent_agent_id,omitempty"`
	ProjectId     string         `json:"project_id"`
	Prompt        *string        `json:"prompt,omitempty"`
	Settings      *SettingsPatch `json:"settings,omitempty"`
	Title         *string        `json:"title,omitempty"`

	// WorkingDirectory Absolute server-local project root or established managed worktree path. Overrides implicit parent workspace inheritance; worktree mode still creates a fresh worktree.
	WorkingDirectory *string             `json:"working_directory,omitempty"`
	Workspace        *WorkspaceSelection `json:"workspace,omitempty"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Defaults          Settings            `json:"defaults"`
	Name              string              `json:"name"`
	Root              string              `json:"root"`
	WorkspaceDefaults *WorkspaceSelection `json:"workspace_defaults,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    ErrorCode `json:"code"`
		Message string    `json:"message"`
	} `json:"error"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Event defines model for Event.
type Event struct {
	AgentId   string    `json:"agent_id"`
	CreatedAt time.Time `json:"created_at"`
	Cursor    int64     `json:"cursor"`

	// Data Payload selected by Event.type; see x-event-data-schemas on Event and websocket.md.
	Data EventData `json:"data"`
	Type EventType `json:"type"`
}

// EventType defines model for Event.Type.
type EventType string

// EventData Payload selected by Event.type; see x-event-data-schemas on Event and websocket.md.
type EventData struct {
	union json.RawMessage
}

// EventPage defines model for EventPage.
type EventPage struct {
	Events     []Event `json:"events"`
	NextCursor int64   `json:"next_cursor"`
}

// FunctionCall defines model for FunctionCall.
type FunctionCall struct {
	// Arguments JSON-encoded function arguments.
	Arguments string `json:"arguments"`
	Name      string `json:"name"`
}

// Health defines model for Health.
type Health struct {
	ApiVersion HealthApiVersion `json:"api_version"`
}

// HealthApiVersion defines model for Health.ApiVersion.
type HealthApiVersion string

// HistoryPage defines model for HistoryPage.
type HistoryPage struct {
	Messages   []Message `json:"messages"`
	NextCursor int64     `json:"next_cursor"`
}

// ImageURL defines model for ImageURL.
type ImageURL struct {
	Detail               *string                `json:"detail,omitempty"`
	Url                  string                 `json:"url"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Message Provider-neutral retained conversation message, including reasoning provenance and tool results. Unknown provider fields are preserved.
type Message struct {
	// Content Original provider body: plain text, typed multimodal parts, or null. Replayed without normalization.
	Content          *MessageContent    `json:"content"`
	Reasoning        *string            `json:"reasoning,omitempty"`
	ReasoningDetails *[]ReasoningDetail `json:"reasoning_details,omitempty"`
	Role             string             `json:"role"`

	// SourceModel Origin model for opaque reasoning replay; not forwarded as a provider message field.
	SourceModel          *string                `json:"source_model,omitempty"`
	ToolCallId           *string                `json:"tool_call_id,omitempty"`
	ToolCalls            *[]ToolCall            `json:"tool_calls,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MessageContent Original provider body: plain text, typed multimodal parts, or null. Replayed without normalization.
type MessageContent struct {
	union json.RawMessage
}

// MessageContent0 defines model for .
type MessageContent0 = string

// MessageContent1 defines model for .
type MessageContent1 = []ContentPart

// Model defines model for Model.
type Model struct {
	ContextWindow int64    `json:"context_window"`
	DefaultEffort string   `json:"default_effort"`
	Efforts       []string `json:"efforts"`
	Id            string   `json:"id"`
	Name          string   `json:"name"`
	Provider      string   `json:"provider"`
}

// NullableSettings defines model for NullableSettings.
type NullableSettings struct {
	Effort string `json:"effort"`
	Model  string `json:"model"`
}

// PatchAgentRequest defines model for PatchAgentRequest.
type PatchAgentRequest struct {
	ReadCursor *int64 `json:"read_cursor,omitempty"`
	Settled    *bool  `json:"settled,omitempty"`
}

// PatchProjectRequest defines model for PatchProjectRequest.
type PatchProjectRequest struct {
	Defaults          *Settings           `json:"defaults,omitempty"`
	Name              *string             `json:"name,omitempty"`
	WorkspaceDefaults *WorkspaceSelection `json:"workspace_defaults,omitempty"`
}

// Project defines model for Project.
type Project struct {
	Defaults Settings `json:"defaults"`

	// GitBranch Live server-side Git branch (or detached commit), populated on GET project; omitted outside Git repositories.
	GitBranch         *string             `json:"git_branch,omitempty"`
	Id                string              `json:"id"`
	Name              string              `json:"name"`
	Root              string              `json:"root"`
	WorkspaceDefaults *WorkspaceSelection `json:"workspace_defaults,omitempty"`
}

// ProjectBranches defines model for ProjectBranches.
type ProjectBranches struct {
	Branches      []string `json:"branches"`
	DefaultBranch string   `json:"default_branch"`
	IsGit         bool     `json:"is_git"`
}

// QueuedMessage defines model for QueuedMessage.
type QueuedMessage struct {
	CreatedAt time.Time           `json:"created_at"`
	Error     *string             `json:"error,omitempty"`
	Id        string              `json:"id"`
	Status    QueuedMessageStatus `json:"status"`
	Text      string              `json:"text"`
}

// QueuedMessageStatus defines model for QueuedMessage.Status.
type QueuedMessageStatus string

// ReasoningDetail Opaque extended thinking record. Unknown provider fields, encrypted data and signatures must be preserved unchanged.
type ReasoningDetail struct {
	Data                 *json.RawMessage       `json:"data"`
	Format               *string                `json:"format,omitempty"`
	Id                   *string                `json:"id,omitempty"`
	Index                *int64                 `json:"index,omitempty"`
	Signature            *string                `json:"signature,omitempty"`
	Summary              *json.RawMessage       `json:"summary"`
	Text                 *string                `json:"text,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Settings defines model for Settings.
type Settings struct {
	Effort string `json:"effort"`
	Model  string `json:"model"`
}

// SettingsPatch defines model for SettingsPatch.
type SettingsPatch struct {
	Effort *string `json:"effort,omitempty"`
	Model  *string `json:"model,omitempty"`
}

// StopRequest defines model for StopRequest.
type StopRequest struct {
	TurnId string `json:"turn_id"`
}

// SubmitMessageRequest defines model for SubmitMessageRequest.
type SubmitMessageRequest struct {
	Text string `json:"text"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	Function FunctionCall `json:"function"`
	Id       string       `json:"id"`
	Index    int64        `json:"index"`
	Type     string       `json:"type"`
}

// WSAck defines model for WSAck.
type WSAck struct {
	AgentId   string    `json:"agent_id"`
	MessageId string    `json:"message_id"`
	RequestId string    `json:"request_id"`
	Status    string    `json:"status"`
	Type      WSAckType `json:"type"`
}

// WSAckType defines model for WSAck.Type.
type WSAckType string

// WSError defines model for WSError.
type WSError struct {
	Code      ErrorCode   `json:"code"`
	Message   string      `json:"message"`
	RequestId *string     `json:"request_id,omitempty"`
	Type      WSErrorType `json:"type"`
}

// WSErrorType defines model for WSError.Type.
type WSErrorType string

// WSEvent defines model for WSEvent.
type WSEvent struct {
	Event Event       `json:"event"`
	Type  WSEventType `json:"type"`
}

// WSEventType defines model for WSEvent.Type.
type WSEventType string

// WSEventReference defines model for WSEventReference.
type WSEventReference struct {
	AgentId string               `json:"agent_id"`
	Cursor  int64                `json:"cursor"`
	Type    WSEventReferenceType `json:"type"`
	Url     string               `json:"url"`
}

// WSEventReferenceType defines model for WSEventReference.Type.
type WSEventReferenceType string

// WSInventory defines model for WSInventory.
type WSInventory struct {
	Agent AgentSummary    `json:"agent"`
	Type  WSInventoryType `json:"type"`
}

// WSInventoryType defines model for WSInventory.Type.
type WSInventoryType string

// WSSubmit defines model for WSSubmit.
type WSSubmit struct {
	AgentId        string       `json:"agent_id"`
	IdempotencyKey string       `json:"idempotency_key"`
	RequestId      string       `json:"request_id"`
	Text           string       `json:"text"`
	Type           WSSubmitType `json:"type"`
}

// WSSubmitType defines model for WSSubmit.Type.
type WSSubmitType string

// WSSubscribe defines model for WSSubscribe.
type WSSubscribe struct {
	AgentIds     *[]string         `json:"agent_ids,omitempty"`
	Cursors      *map[string]int64 `json:"cursors,omitempty"`
	RequestId    string            `json:"request_id"`
	SubscribeAll *bool             `json:"subscribe_all,omitempty"`
	Type         WSSubscribeType   `json:"type"`
}

// WSSubscribeType defines model for WSSubscribe.Type.
type WSSubscribeType string

// WSSubscribed defines model for WSSubscribed.
type WSSubscribed struct {
	RequestId string           `json:"request_id"`
	Type      WSSubscribedType `json:"type"`
}

// WSSubscribedType defines model for WSSubscribed.Type.
type WSSubscribedType string

// Workspace defines model for Workspace.
type Workspace struct {
	BaseBranch *string       `json:"base_branch,omitempty"`
	BaseCommit *string       `json:"base_commit,omitempty"`
	Branch     *string       `json:"branch,omitempty"`
	Error      *string       `json:"error,omitempty"`
	Locked     bool          `json:"locked"`
	Mode       WorkspaceMode `json:"mode"`
	Path       *string       `json:"path,omitempty"`

	// Shared Reuses an existing managed worktree rather than provisioning a new one.
	Shared *bool           `json:"shared,omitempty"`
	Status WorkspaceStatus `json:"status"`
}

// WorkspaceMode defines model for Workspace.Mode.
type WorkspaceMode string

// WorkspaceStatus defines model for Workspace.Status.
type WorkspaceStatus string

// WorkspaceSelection defines model for WorkspaceSelection.
type WorkspaceSelection struct {
	BaseBranch *string                `json:"base_branch,omitempty"`
	Mode       WorkspaceSelectionMode `json:"mode"`
}

// WorkspaceSelectionMode defines model for WorkspaceSelection.Mode.
type WorkspaceSelectionMode string

// ListAgentsParams defines parameters for ListAgents.
type ListAgentsParams struct {
	IncludeSettled *bool   `form:"include_settled,omitempty" json:"include_settled,omitempty"`
	ProjectId      *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// CreateAgentParams defines parameters for CreateAgent.
type CreateAgentParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	After *int64 `form:"after,omitempty" json:"after,omitempty"`
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetHistoryParams defines parameters for GetHistory.
type GetHistoryParams struct {
	After *int64 `form:"after,omitempty" json:"after,omitempty"`
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// SubmitMessageParams defines parameters for SubmitMessage.
type SubmitMessageParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = CreateAgentRequest

// PatchAgentJSONRequestBody defines body for PatchAgent for application/json ContentType.
type PatchAgentJSONRequestBody = PatchAgentRequest

// SubmitMessageJSONRequestBody defines body for SubmitMessage for application/json ContentType.
type SubmitMessageJSONRequestBody = SubmitMessageRequest

// PatchAgentSettingsJSONRequestBody defines body for PatchAgentSettings for application/json ContentType.
type PatchAgentSettingsJSONRequestBody = SettingsPatch

// StopAgentJSONRequestBody defines body for StopAgent for application/json ContentType.
type StopAgentJSONRequestBody = StopRequest

// PatchAgentWorkspaceJSONRequestBody defines body for PatchAgentWorkspace for application/json ContentType.
type PatchAgentWorkspaceJSONRequestBody = WorkspaceSelection

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// PatchProjectJSONRequestBody defines body for PatchProject for application/json ContentType.
type PatchProjectJSONRequestBody = PatchProjectRequest

// Getter for additional properties for ContentPart. Returns the specified
// element and whether it was found
func (a ContentPart) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContentPart
func (a *ContentPart) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContentPart to handle AdditionalProperties
func (a *ContentPart) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["image_url"]; found {
		err = json.Unmarshal(raw, &a.ImageUrl)
		if err != nil {
			return fmt.Errorf("error reading 'image_url': %w", err)
		}
		delete(object, "image_url")
	}

	if raw, found := object["text"]; found {
		err = json.Unmarshal(raw, &a.Text)
		if err != nil {
			return fmt.Errorf("error reading 'text': %w", err)
		}
		delete(object, "text")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContentPart to handle AdditionalProperties
func (a ContentPart) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ImageUrl != nil {
		object["image_url"], err = json.Marshal(a.ImageUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'image_url': %w", err)
		}
	}

	if a.Text != nil {
		object["text"], err = json.Marshal(a.Text)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'text': %w", err)
		}
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ImageURL. Returns the specified
// element and whether it was found
func (a ImageURL) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ImageURL
func (a *ImageURL) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ImageURL to handle AdditionalProperties
func (a *ImageURL) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &a.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
		delete(object, "url")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ImageURL to handle AdditionalProperties
func (a ImageURL) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["url"], err = json.Marshal(a.Url)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'url': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Message. Returns the specified
// element and whether it was found
func (a Message) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Message
func (a *Message) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Message to handle AdditionalProperties
func (a *Message) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return fmt.Errorf("error reading 'content': %w", err)
		}
		delete(object, "content")
	}

	if raw, found := object["reasoning"]; found {
		err = json.Unmarshal(raw, &a.Reasoning)
		if err != nil {
			return fmt.Errorf("error reading 'reasoning': %w", err)
		}
		delete(object, "reasoning")
	}

	if raw, found := object["reasoning_details"]; found {
		err = json.Unmarshal(raw, &a.ReasoningDetails)
		if err != nil {
			return fmt.Errorf("error reading 'reasoning_details': %w", err)
		}
		delete(object, "reasoning_details")
	}

	if raw, found := object["role"]; found {
		err = json.Unmarshal(raw, &a.Role)
		if err != nil {
			return fmt.Errorf("error reading 'role': %w", err)
		}
		delete(object, "role")
	}

	if raw, found := object["source_model"]; found {
		err = json.Unmarshal(raw, &a.SourceModel)
		if err != nil {
			return fmt.Errorf("error reading 'source_model': %w", err)
		}
		delete(object, "source_model")
	}

	if raw, found := object["tool_call_id"]; found {
		err = json.Unmarshal(raw, &a.ToolCallId)
		if err != nil {
			return fmt.Errorf("error reading 'tool_call_id': %w", err)
		}
		delete(object, "tool_call_id")
	}

	if raw, found := object["tool_calls"]; found {
		err = json.Unmarshal(raw, &a.ToolCalls)
		if err != nil {
			return fmt.Errorf("error reading 'tool_calls': %w", err)
		}
		delete(object, "tool_calls")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Message to handle AdditionalProperties
func (a Message) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["content"], err = json.Marshal(a.Content)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'content': %w", err)
	}

	if a.Reasoning != nil {
		object["reasoning"], err = json.Marshal(a.Reasoning)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reasoning': %w", err)
		}
	}

	if a.ReasoningDetails != nil {
		object["reasoning_details"], err = json.Marshal(a.ReasoningDetails)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reasoning_details': %w", err)
		}
	}

	object["role"], err = json.Marshal(a.Role)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'role': %w", err)
	}

	if a.SourceModel != nil {
		object["source_model"], err = json.Marshal(a.SourceModel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'source_model': %w", err)
		}
	}

	if a.ToolCallId != nil {
		object["tool_call_id"], err = json.Marshal(a.ToolCallId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tool_call_id': %w", err)
		}
	}

	if a.ToolCalls != nil {
		object["tool_calls"], err = json.Marshal(a.ToolCalls)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tool_calls': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ReasoningDetail. Returns the specified
// element and whether it was found
func (a ReasoningDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ReasoningDetail
func (a *ReasoningDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ReasoningDetail to handle AdditionalProperties
func (a *ReasoningDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["data"]; found {
		err = json.Unmarshal(raw, &a.Data)
		if err != nil {
			return fmt.Errorf("error reading 'data': %w", err)
		}
		delete(object, "data")
	}

	if raw, found := object["format"]; found {
		err = json.Unmarshal(raw, &a.Format)
		if err != nil {
			return fmt.Errorf("error reading 'format': %w", err)
		}
		delete(object, "format")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["index"]; found {
		err = json.Unmarshal(raw, &a.Index)
		if err != nil {
			return fmt.Errorf("error reading 'index': %w", err)
		}
		delete(object, "index")
	}

	if raw, found := object["signature"]; found {
		err = json.Unmarshal(raw, &a.Signature)
		if err != nil {
			return fmt.Errorf("error reading 'signature': %w", err)
		}
		delete(object, "signature")
	}

	if raw, found := object["summary"]; found {
		err = json.Unmarshal(raw, &a.Summary)
		if err != nil {
			return fmt.Errorf("error reading 'summary': %w", err)
		}
		delete(object, "summary")
	}

	if raw, found := object["text"]; found {
		err = json.Unmarshal(raw, &a.Text)
		if err != nil {
			return fmt.Errorf("error reading 'text': %w", err)
		}
		delete(object, "text")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ReasoningDetail to handle AdditionalProperties
func (a ReasoningDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Data != nil {
		object["data"], err = json.Marshal(a.Data)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'data': %w", err)
		}
	}

	if a.Format != nil {
		object["format"], err = json.Marshal(a.Format)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'format': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Index != nil {
		object["index"], err = json.Marshal(a.Index)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'index': %w", err)
		}
	}

	if a.Signature != nil {
		object["signature"], err = json.Marshal(a.Signature)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'signature': %w", err)
		}
	}

	if a.Summary != nil {
		object["summary"], err = json.Marshal(a.Summary)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'summary': %w", err)
		}
	}

	if a.Text != nil {
		object["text"], err = json.Marshal(a.Text)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'text': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsImageURL returns the union data inside the ContentPart_ImageUrl as a ImageURL
func (t ContentPart_ImageUrl) AsImageURL() (ImageURL, error) {
	var body ImageURL
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURL overwrites any union data inside the ContentPart_ImageUrl as the provided ImageURL
func (t *ContentPart_ImageUrl) FromImageURL(v ImageURL) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURL performs a merge with any union data inside the ContentPart_ImageUrl, using the provided ImageURL
func (t *ContentPart_ImageUrl) MergeImageURL(v ImageURL) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentPartImageUrl1 returns the union data inside the ContentPart_ImageUrl as a ContentPartImageUrl1
func (t ContentPart_ImageUrl) AsContentPartImageUrl1() (ContentPartImageUrl1, error) {
	var body ContentPartImageUrl1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentPartImageUrl1 overwrites any union data inside the ContentPart_ImageUrl as the provided ContentPartImageUrl1
func (t *ContentPart_ImageUrl) FromContentPartImageUrl1(v ContentPartImageUrl1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentPartImageUrl1 performs a merge with any union data inside the ContentPart_ImageUrl, using the provided ContentPartImageUrl1
func (t *ContentPart_ImageUrl) MergeContentPartImageUrl1(v ContentPartImageUrl1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart_ImageUrl) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart_ImageUrl) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAgentUpdate returns the union data inside the EventData as a AgentUpdate
func (t EventData) AsAgentUpdate() (AgentUpdate, error) {
	var body AgentUpdate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentUpdate overwrites any union data inside the EventData as the provided AgentUpdate
func (t *EventData) FromAgentUpdate(v AgentUpdate) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentUpdate performs a merge with any union data inside the EventData, using the provided AgentUpdate
func (t *EventData) MergeAgentUpdate(v AgentUpdate) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQueuedMessage returns the union data inside the EventData as a QueuedMessage
func (t EventData) AsQueuedMessage() (QueuedMessage, error) {
	var body QueuedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueuedMessage overwrites any union data inside the EventData as the provided QueuedMessage
func (t *EventData) FromQueuedMessage(v QueuedMessage) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueuedMessage performs a merge with any union data inside the EventData, using the provided QueuedMessage
func (t *EventData) MergeQueuedMessage(v QueuedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentOutput returns the union data inside the EventData as a AgentOutput
func (t EventData) AsAgentOutput() (AgentOutput, error) {
	var body AgentOutput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentOutput overwrites any union data inside the EventData as the provided AgentOutput
func (t *EventData) FromAgentOutput(v AgentOutput) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentOutput performs a merge with any union data inside the EventData, using the provided AgentOutput
func (t *EventData) MergeAgentOutput(v AgentOutput) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConversationDelta returns the union data inside the EventData as a ConversationDelta
func (t EventData) AsConversationDelta() (ConversationDelta, error) {
	var body ConversationDelta
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConversationDelta overwrites any union data inside the EventData as the provided ConversationDelta
func (t *EventData) FromConversationDelta(v ConversationDelta) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConversationDelta performs a merge with any union data inside the EventData, using the provided ConversationDelta
func (t *EventData) MergeConversationDelta(v ConversationDelta) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventData) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventData) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMessageContent0 returns the union data inside the MessageContent as a MessageContent0
func (t MessageContent) AsMessageContent0() (MessageContent0, error) {
	var body MessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageContent0 overwrites any union data inside the MessageContent as the provided MessageContent0
func (t *MessageContent) FromMessageContent0(v MessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageContent0 performs a merge with any union data inside the MessageContent, using the provided MessageContent0
func (t *MessageContent) MergeMessageContent0(v MessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageContent1 returns the union data inside the MessageContent as a MessageContent1
func (t MessageContent) AsMessageContent1() (MessageContent1, error) {
	var body MessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageContent1 overwrites any union data inside the MessageContent as the provided MessageContent1
func (t *MessageContent) FromMessageContent1(v MessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageContent1 performs a merge with any union data inside the MessageContent, using the provided MessageContent1
func (t *MessageContent) MergeMessageContent1(v MessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MessageContent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MessageContent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /v1/agents)
	ListAgents(w http.ResponseWriter, r *http.Request, params ListAgentsParams)

	// (POST /v1/agents)
	CreateAgent(w http.ResponseWriter, r *http.Request, params CreateAgentParams)

	// (GET /v1/agents/{agent_id})
	GetAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (PATCH /v1/agents/{agent_id})
	PatchAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (POST /v1/agents/{agent_id}/continue)
	ContinueAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (GET /v1/agents/{agent_id}/events)
	GetEvents(w http.ResponseWriter, r *http.Request, agentId string, params GetEventsParams)

	// (GET /v1/agents/{agent_id}/events/{cursor})
	GetEvent(w http.ResponseWriter, r *http.Request, agentId string, cursor int64)

	// (GET /v1/agents/{agent_id}/history)
	GetHistory(w http.ResponseWriter, r *http.Request, agentId string, params GetHistoryParams)

	// (GET /v1/agents/{agent_id}/messages)
	ListMessages(w http.ResponseWriter, r *http.Request, agentId string)

	// (POST /v1/agents/{agent_id}/messages)
	SubmitMessage(w http.ResponseWriter, r *http.Request, agentId string, params SubmitMessageParams)

	// (DELETE /v1/agents/{agent_id}/messages/{message_id})
	DeletePending(w http.ResponseWriter, r *http.Request, agentId string, messageId string)

	// (PATCH /v1/agents/{agent_id}/settings)
	PatchAgentSettings(w http.ResponseWriter, r *http.Request, agentId string)

	// (POST /v1/agents/{agent_id}/stop)
	StopAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (PATCH /v1/agents/{agent_id}/workspace)
	PatchAgentWorkspace(w http.ResponseWriter, r *http.Request, agentId string)

	// (GET /v1/models)
	ListModels(w http.ResponseWriter, r *http.Request)

	// (GET /v1/projects)
	ListProjects(w http.ResponseWriter, r *http.Request)

	// (POST /v1/projects)
	CreateProject(w http.ResponseWriter, r *http.Request)

	// (DELETE /v1/projects/{project_id})
	DeleteProject(w http.ResponseWriter, r *http.Request, projectId string)

	// (GET /v1/projects/{project_id})
	GetProject(w http.ResponseWriter, r *http.Request, projectId string)

	// (PATCH /v1/projects/{project_id})
	PatchProject(w http.ResponseWriter, r *http.Request, projectId string)

	// (GET /v1/projects/{project_id}/branches)
	ListProjectBranches(w http.ResponseWriter, r *http.Request, projectId string)

	// (GET /v1/ws)
	WebSocket(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentsParams

	// ------------- Optional query parameter "include_settled" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_settled", r.URL.Query(), &params.IncludeSettled)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_settled", Err: err})
		return
	}

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAgent operation middleware
func (siw *ServerInterfaceWrapper) CreateAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateAgentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgent operation middleware
func (siw *ServerInterfaceWrapper) GetAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAgent operation middleware
func (siw *ServerInterfaceWrapper) PatchAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ContinueAgent operation middleware
func (siw *ServerInterfaceWrapper) ContinueAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ContinueAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// ------------- Path parameter "cursor" -------------
	var cursor int64

	err = runtime.BindStyledParameterWithOptions("simple", "cursor", r.PathValue("cursor"), &cursor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, agentId, cursor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHistory operation middleware
func (siw *ServerInterfaceWrapper) GetHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHistoryParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHistory(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitMessage operation middleware
func (siw *ServerInterfaceWrapper) SubmitMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SubmitMessageParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitMessage(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePending operation middleware
func (siw *ServerInterfaceWrapper) DeletePending(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// ------------- Path parameter "message_id" -------------
	var messageId string

	err = runtime.BindStyledParameterWithOptions("simple", "message_id", r.PathValue("message_id"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "message_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePending(w, r, agentId, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAgentSettings operation middleware
func (siw *ServerInterfaceWrapper) PatchAgentSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAgentSettings(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopAgent operation middleware
func (siw *ServerInterfaceWrapper) StopAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAgentWorkspace operation middleware
func (siw *ServerInterfaceWrapper) PatchAgentWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAgentWorkspace(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchProject operation middleware
func (siw *ServerInterfaceWrapper) PatchProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectBranches operation middleware
func (siw *ServerInterfaceWrapper) ListProjectBranches(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectBranches(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WebSocket operation middleware
func (siw *ServerInterfaceWrapper) WebSocket(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WebSocket(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents", wrapper.ListAgents)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents", wrapper.CreateAgent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}", wrapper.GetAgent)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/agents/{agent_id}", wrapper.PatchAgent)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents/{agent_id}/continue", wrapper.ContinueAgent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/events", wrapper.GetEvents)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/events/{cursor}", wrapper.GetEvent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/history", wrapper.GetHistory)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/messages", wrapper.ListMessages)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents/{agent_id}/messages", wrapper.SubmitMessage)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/agents/{agent_id}/messages/{message_id}", wrapper.DeletePending)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/agents/{agent_id}/settings", wrapper.PatchAgentSettings)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents/{agent_id}/stop", wrapper.StopAgent)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/agents/{agent_id}/workspace", wrapper.PatchAgentWorkspace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/models", wrapper.ListModels)
	m.HandleFunc("GET "+options.BaseURL+"/v1/projects", wrapper.ListProjects)
	m.HandleFunc("POST "+options.BaseURL+"/v1/projects", wrapper.CreateProject)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/projects/{project_id}", wrapper.DeleteProject)
	m.HandleFunc("GET "+options.BaseURL+"/v1/projects/{project_id}", wrapper.GetProject)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/projects/{project_id}", wrapper.PatchProject)
	m.HandleFunc("GET "+options.BaseURL+"/v1/projects/{project_id}/branches", wrapper.ListProjectBranches)
	m.HandleFunc("GET "+options.BaseURL+"/v1/ws", wrapper.WebSocket)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9W3Mbt5L/V+ni//+QVFGUlDhnN9KTLTs5PhtbXsupPJxK8YAzTRIRBhgDGEqMS999",
	"Cw3MlcOrJVlx8GSLM8CgGw38+gp8GiQqy5VEac3g7NPAJHPMGP33+Qyldf9hacotV5KJd1rlqC1HMzib",
	"MmFwOMgbP30asMTyBY4NWsvljH76/xqng7PB/zuuP3QcvnJ8Vb53NxwkSlq8tePCsBlua3jhX/6V3nWN",
	"NTKL6ZjRgKdKZ+5/g5RZPLI8w8FwYJc5Ds4GxmouZ9Sm0Ebp1vtc2n88GwwHGZc8K7LB2UnVjkuLM9Su",
	"4RxF6pqFJxOlBDLpnnD6PWO3v6Cc2fng7Lsf/kG9lX+f9oxDMGPHGk2upMHxwaPK0DhuEM+5xWwr89/4",
	"Bq5t6I1pzZbu75xplHbMnASMDyIq1+oPTA5s/LHAAnem43/d2+kGajSy9HC+HiLLro3ANUJiLLNEHUr3",
	"0X8PeCqcgOpCSscA94bKc/ff33uYY7kV2Oi5flLk6d6L4Ebpa5OzZOuK+6168Y5Y+rHg2lHohj9ozXc5",
	"xAbrao6U5IdVVK3C1hJukVLzQE3cJ9yoaWu6LGxebN+gUjSJ5rl7PjgbvEfLuMQUSLZH1NH7sPZG8I6Z",
	"hIkLZhCmHEUKkmVogGkEJxHSfwQce5jlEy64XcINt3OwcwS85cbRC7qQjt+gaISQs6VQLB0Nursl7WJ+",
	"j22P8iU3uWDL41yrBU9RH4XNMfQ4hFwZwydiCQnLc0xhqjRYpQRoNIWwZtQ31z8VQnxQStSMa3/1QmW5",
	"QItQyNAtdWlsqgp7bGyKWgOXiShSR2XCZIJCMNf6eMq4KDQCk1JZ+smcA2a5XYKSIJU8cn0d+eEFMnoH",
	"WU7GB3pQLxKaL9dAKRH+GfvegkwVTsw8ePQtG0f4BRPi9cveteMev2VZ38LqiHs5aZ2htr7Q6G+F7Wvl",
	"+arIMqaXEXH/Koj7hVEywtpXCWu/0jt7wtqV+3oJNIQGHt/C14HJEvHCEEbwwSGWTIQybjN/tUBpwRR5",
	"LrhDvCDTQ/CEUAc1Ka41N8ANSGWBESASchAFDoRUoRM8B24hRcEnqJlFsQS8deiBBubcWKWX1C+pe6vo",
	"uOfO9rYQgk0E3tsOFzedv/Gm81gbSFfIN20pLWHu2z+CavKO6Q1qsdXFihLBMzbDcaGF+0NJvJwOzv69",
	"me7Xrsmv738Z3A1X2Pe7Yy3e2l7O2qDYbday6OlaGstVup+qVDLwhstU3fSK76rIorE8c9tevwBWj8dW",
	"XaM0O/bKZV7Y/ZpcS3Uj+weRqRRFL7O9or3Phzrz4LvuDLjbbw8bhl1ulwQ0ObpmfheoDZkQL1FYtmqn",
	"vMUbhzgZtw7aSr8HOJNFppiC4TJBsshyjQuuCgNJo1dAh3XDAF3TQoj2YyNZbuaKzJPPdaRcEGQGK/Nj",
	"gWZfe9V3YIBJcFubB2YopEBjINcqy62D4QDc6Qgu82CkdoACssJY4KkzYqcOd2tz1fepJFgH6gb1Aj3g",
	"O4jPssI6WAU2tai9DsCVHMFl4H/KNSYVllf7JqgFas0d1ps5I8sQ0LiuuJljGoZH71uNzr6mGTMsc9NG",
	"m+Y5KDtHfcNN9ROkOGXOwHWzLZarSsMXhkc/I52GpyfP/vuH/9reeF90fMdsMm/BWHe0vbDG5WxcTdrq",
	"6no+MUoUFoMgHAmVOGkK/NdKWVC6NZUZk2yGaT2XObPzEVxWAsCzXPCE2+akeyHhco6aWyadsli1d5sO",
	"GMvdyizlH6Yazbx6x818g9pnJz9u5+/+mH6FAhPiS3dfbEhJ7y5Gw37nX9p15bcluZT0fXQlGTwY+yp1",
	"SnVldj+Gjncd7A6cld5rQmMa1lzo4/Irrb0augdb8YA2iUq3ygyN5cK9WPvit6s51HP9/iqRnff96Nfy",
	"4iIMtNKG5YIJUj3D/8ZBbhu/NFTP8qd6oTTnWKjkmvTS+qcp46LzUyHZgnGyxBo9lgTWvwiecfLnFVqO",
	"KxKHA6nseKoKGTTeqeA02nK9EWiZxg/uffIzur5TzHJlUSbLcaOte8WpBt4gcH81zINK2/ZGzbhmmZkX",
	"xJlx6vUWZ7A6Nbki2ulMWjJBE2jnKqXBMCHUDT23So0F00R2IR1EK+1UpAxTzsbWew2nSk94mqLsNVDI",
	"LN/XI3g49j2UU++0T6FNmVfuNq4qR/9L92LDcmi5hEsXh7Olmg6OelWNyL/Q/CF4rv0kFVqOjGXa1n+W",
	"7ozqh2rK6S+ad13kzRaNHr1u7MW30ip7ZreztKtpaziPgowQp1qzs7IDDAe3R6TXHrmXjxph3DaX1vC5",
	"6XnqMnKnJi1a1ztYOqp935TsFOVbmdwdW4W52UTSZTl9nYnd8QsdAdqnVZCyfZo0RXGfdqXA7xZSLTei",
	"l6zPHHsXvI6GIB1TmCy9O3HkRPQcDCL0CaezOLzbkQwHnBgHMHaUUaRsNy9EUwjvhvvFiXfoOcjCtndX",
	"BZtcIETcu/39FMSq3eP4HiN6jE/pzO8DfXVdvcMPqd1nnxryUyFJrbtgQuyLW3pWZCXlbRH719Xl2yOU",
	"TltKYRo+AVWD3kCi3CmaF7TN+tt9RP0TmXCQuR85OR87qSAKatA63QEJGi17h+N95wdI1n3miNyjdFXD",
	"2i5fldtxL/9mipbxfg9ZcHpunhH3Ut9o3tR6/qbBdPbLMqgvsbCaCdBlTkLLDRWYMmxE3DUyo5zi6szx",
	"BUqHTbR5tkL/8KskVxuU2QM+l8GnMeQaya7vyUZI6myEHUSiDIP7mIAfVi+Dq6djPwu7C9/7suVLP319",
	"qT1qjf/eB6DGlWe0PQWXms+4JD+DoGiZytnHAhsM1pgLtjwnJ+FU6Rum3dbDDLCarWGGPHt79yDKUkiY",
	"EEEdX//C7lwp0wxW2dERWuLNsJrWDfK7Ng/F88m7fzzNE5UuzyAXjEuweGuH4DpNISuE5ZlKvePRmiEo",
	"DbIQYgTviZWYUqKMKixIt1UI/qd3JLpFH0J35Xqpsb/LsB151AyErLDJQfObUi7uN3ywOfoVfBljnE6V",
	"7g+O+EdtYVgTQakXwRrZWgOARBZN5vZ9j6yRAJFVqx7XfjnsFRr7hG4lULttGrri0dGWKm42jN1/POtZ",
	"jdVmsJdVvCYgsoFA8svu5fPP2G3z11MaUueXNtWfH4ddE1O9W0fQns7MbQQ8onvz3tyUq4wJ3rSH9+zO",
	"uB1PNJPJfHWX/oUvKm+94SnCz9yCfxm+URoc7iZz0i+yjNtvh5CrvBCUGKIk/PzqQyPiEqI6qrBVVxpz",
	"ZbhVmmO/qn2Qr2nt9lR6ox/H3dzc4nbxOYcpf0HsRbPn1E8azXbf4MtNtRaA1Skw4xm3axZ0i17/4rAe",
	"ykr/fWS3jec9gfMAr2Llpr8fYQsJog07rHYI187gpt+v7eWtvH21P6g3n6Q/6aFP5OjVRubqJucepcW2",
	"deG9LI5Lr93irfUBcjvn8tpruYnS6VqLYQgoE73MKczLLCNbw/CZZLbQaHxIedIwKqCQyZzJWZ95Ubp7",
	"u2h+ezRTR4HeP4ySo/fspmF2luKyVhJWf5Yp3h4CiiVh/QZFnZ27JwUHZMKsTP/OutJT143asevPVSIe",
	"gb5VCqzKD4voUqjrgO2rmxoVuullbzHJuA3Cd+Aog7juncDQHabrp2+MlQG737hKt982zG95IO9/l9gt",
	"fc1v8T564780rAnoY8pvV8+T68cL9AXXxaE5oCRX489E4rX7YRXfS663O0sDkxtjGjZDaQ1Cq2/38//V",
	"l00M6LJ1K3e6qQCb+bM10YBYcEC0GRc7+Aw7IYoGEYu2a2ozEd23V8b+HqeoUSb4iCHzQ8PfvawYOyb2",
	"aZY7uakDm/oiyes82L9dvZbuw2r/wqPZDhPfKmzqIZpXH99VBvxn+0nx6Pd4c9/MN7nG5WNvpQcj9eo8",
	"GM+5z91tuwwZrtcCaLackTI5dLG2jeh9edcxsf1C2aBfH6goNCj+PNgsmTUOmlOw2SserWaF98xx4PcB",
	"07xlCtM95/Dz5H4dYem9UdbMFN3HvcMMNrw0rYX53bOthFFz76TrVQE2+H/W+0tC2t7awoEmJ5NCU/p0",
	"MsfkWlEWTJlw24tKObP9w6GU73TVVfkeC+Oz2avs85XsYc3sHDXYOQsOCcN9TI6BxBtQEhtOyE4tUNvH",
	"k2o2dTRM0Sbz4OKh/HXv90GWLmtPz++7WLeDip+btclVv+OjCtLnzWsf3T2ZqWRETVWPP5oyxgvJCjtH",
	"aXlCnuZESauVgFwwiSN4wSluDUKpfMKS60ZNg63SiBhYXRj3R67V7XIEz4WAsHbBD8SARspML2ofVmDk",
	"CF6/NL5y0e/uFAEvQ72hRj9URHDU5rz1nlRS4oxZvvDF/zPUZgQvVMrRAGWvUoE8fAdv+IsR/Ovq8i3Q",
	"KiwLHpREQLlAoXIcwVsFN1ykCdMpXFy+vxpV9WBngw9d9sDzd68Hw0GVPjI4HZ2MTqigJ0fJcj44G3w/",
	"Ohl9P/BrkGTmeF6lqcywJ5j7M9qQyELdaAq/vk47T8oKReryu5OTTmYAy3PhJpQrefyH8XLtlb1tqmD4",
	"AslNp3i1SBI0FOZ4do8f9AZdz/de+xTfUpDOKtFRGjJuqB62dIBmTDjcx9RPsNKQM80ytKjNECaqkKmB",
	"BVf+GAQz8kQ8e3giQhxi6Kt3hnW6iNK+wCmkLhQyDYP64eEH9c8PH96Bz4X25VU+FzoM4MeHH8BFyPp2",
	"U0jlk0No6KRwjUvQDoJ8MgKkfEoGY3VGB7GvzOtwFIQwgafg9BGE88LXW4c0dPiGzZGloKZ1lpCxGlnm",
	"BloG6QSfotvMvg3D/P7hhxl8i5QPAnibIKYmbIV+DI8gba9uc48U3b5pCD88zlbiSwDKqjkCgPD5R5iF",
	"K9QLniCUpQqQhm0sLTQV7YWaBWhUZYxcR3fDwfHi9Jj2DrMWMX7hxj6fhczPNmS0HtVbIiXtcNf2Y4F6",
	"WYZWnWFEhf/jRnVzRfo2U4bSfnr6bNVW193t51v//TMhb6d8JH+U2mrCVoTCCIURCiMURij8clA4HOTK",
	"9J2GRgkZwKTfVs5BVZX1vuyeKo8McGtgyrWxQJU1dQH+63q1Hf0PLiFj1+isVaudBWnYFM/DqqOM7lBF",
	"U50mR5XwfpW6jg08O/lxtILDjQMG1gCxWzSUtRlQszOsz4VOkv0XKl3e2xT3nJlw1/ZJWF3g3Qpun97b",
	"CAJcR3iO8BzhOcJzhOenYqkefyqDf3eb3JwlHK54OTfhJMUyKpRsBDXbuPPlLM2IWBGxImJFxIqI9eQN",
	"yjK5ud2jP6cAggvUryHXIUsXrDyxruqcAuignYCGI1itArxliRVLbx+GI9/CjuRfGkFIsIb/hM/8x7Vz",
	"wAXMqownTIhlGIJxewi4MaJMmbSmWWvMEq18ONZHWanMeK5VMZsDExQ7Pyop8eB87i1iH8kHjRnj0sAc",
	"hT9+NpRZgDdmmUaoainC2XI5asON202wpoNbRwB5hkGj4zkaUDIwIcBMOQb6kEC2QNMajBvECF4F7imJ",
	"ZZR4CdxACfAj+EXdoPZz7OUJmzNQxoWPVN6IFU9wqYg3CCHMHsbi5yXsKK6lD1T72oi2alJXDH5R5eT+",
	"bfnVUsidTPmoGEXFKCpGUTGKitHfwZQ/duPl0l/50++Mf48CmUEP6jBXQadwY00LgeWKqQ4Dpnwr3RCX",
	"Hs95+Gj0CUToi9AXoS9CX4S+x4e++qy/NRlYXtLCFiPUbOjvUDF8UR3JHiz/xtFpzqoVzNgQO8bKh6B0",
	"aKRkuJ0rZzMcQblFl0atbwfPTk9G8FMhBJ3mbvif/mSQvLDebvYrZNTnan+12JAc9uC4uiZjjGjvzz07",
	"Ge57hF3/J8pzjXs+cXrS+xF2G6oET9zzTUWDD6ou1KdVRpUhqgxRZYgqQ1QZnrDKcPzJY/X6QPhPaJM5",
	"Obur69kqAQ1X4NTu/oDquiyg9+VX4a6cscYp/IaTKzqgGaZudyULO7SyupBJdZpjvyrwpTWB9oequvj1",
	"n9mrnP/hkTmickTliMoRlSMqP01UDhearkXji56zvU0wxhn8iVodTZjxhcCmyDA9KldTn32PHwsmyua5",
	"KEzD0leFtCN47sT/SE2PyptWV0378/aB43SruT9ZP2PLciFRDnw5ht7K4UB4tPT/KpZ+8/6AqFVErSJq",
	"FVGriFrFk9Qqmhe29KoVr6VxXKf0MwqON416izqj6xtQ2vLw7tUy7jf17St/yRj4ThXY3cufYiV2RMGI",
	"ghEFIwo+/Ups2ruBlUtgQ4l1ilXitgE609IYtwOW2ey0FTCZ1s7s88Zys3hr962/bh24/aVt4L9cqXfv",
	"ceU7ZYh/d29j6N51GTWBqAlETSBqAlETeML28PGn+mD/O68xCLS4qju8pN/fVZf9tNG7+/QJRahbFxc8",
	"nKn9bJVlEe8i3kW8i3gX8e7L451p3Pu1pqr8gi5cg/JNus54WthCoy+1PidrliV0kDWFfq8Rc39uWcJy",
	"92Jatd5UmlzdQfZ1lSi3bySL5ckRhCMIRxCOIBxBuAJhq/L1pclXVuX1gSQO/lIPs9+EixqBe7ANB5KU",
	"K+n1y2/Pq6NfyvplemcEV2yKYBUdFrqs7s1348iri1BQ+wNHV13SVuVf41kizYs3I0xHmI4wHWE6wnSE",
	"6RKmb5qXtm02lh1SV6+DKS/pgglOlfaP/ZHeUklfJl3Fnj/Mmw2ESq4NcK1xoRI2ocPFQlODcuNJX/Ud",
	"c18XTPfcfRbROqJ1ROuI1hGt/65onakUxeaLpt74V3ozlMtHD58nTJ+K+cERSyKWRCyJWPIUsaQ8knoj",
	"mrwrX+rDk8bDh0eU8LGIKRFTIqZETImY8he6/a/cu/tv3aufPtw1eOEbX+givAq7IlZFrIpYFbEqYtXT",
	"sX+OP9UXoO9QAwGsvMyHKiCZEJSV0r7Dhx4lc2YhHBs0gvd1+SPczLlAYHJZva7dMMs+lAZjuRBVpgqt",
	"zDlbICRzLlKNErgEZeeoq5uFfEitHFrKNSZ0XhE3tJY1ZmrRd8ZwqN2oMHh7DK11X3wsqYhgGcEygmUE",
	"y6/VsFt3O+w6o6716MmgyUk05iI+RXyK+BTx6W91S2xpEDm0of782aLmvPofsOnUvRGK/YJFpqRYrkk7",
	"fBro9kCXjB7iKI3YGrE1YmvE1oitfx9H6fFEM5nMcXP6CLkdLR59LJjgU44p/MwtlE3LC9DBb6xcUsWA",
	"UAkTkMwxuVaFpftRJFq6f3xKV7FwAzlqv+GONiWmvCiH+DXboRWRETMjZkbMjJgZMfMJYObNelz8NZ9p",
	"llJdelYIy3OBt9g4SnUEVyzDo7lyQqDVjUENl5rPuPTl8d8oDWxi3NryP397DlOlJzxN0Q3R/VRfT3Ly",
	"/QiuEOEGJ8Z3n6V0tk2ulVWJEueQCO46o+vIfCjyt6urYuLGPCGbmf7MuMdiur2jsVevInBFSTcv9NSn",
	"1HztGPUI4hnkIcR27ZybsE4iTEaYjDAZYfLJw+Td3f8FAAD//2DaScUz7QAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
