//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AgentState.
const (
	AgentStateIdle     AgentState = "idle"
	AgentStateRunning  AgentState = "running"
	AgentStateStopping AgentState = "stopping"
)

// Defines values for AgentOutputResponseType.
const (
	AgentOutputResponseTypeAgent      AgentOutputResponseType = "agent"
	AgentOutputResponseTypeStatus     AgentOutputResponseType = "status"
	AgentOutputResponseTypeTool       AgentOutputResponseType = "tool"
	AgentOutputResponseTypeToolResult AgentOutputResponseType = "tool_result"
	AgentOutputResponseTypeUsage      AgentOutputResponseType = "usage"
)

// Defines values for AgentSummaryState.
const (
	AgentSummaryStateIdle     AgentSummaryState = "idle"
	AgentSummaryStateRunning  AgentSummaryState = "running"
	AgentSummaryStateStopping AgentSummaryState = "stopping"
)

// Defines values for AgentUpdateState.
const (
	AgentUpdateStateIdle     AgentUpdateState = "idle"
	AgentUpdateStateRunning  AgentUpdateState = "running"
	AgentUpdateStateStopping AgentUpdateState = "stopping"
)

// Defines values for ErrorCode.
const (
	Conflict             ErrorCode = "conflict"
	CursorInvalid        ErrorCode = "cursor_invalid"
	Forbidden            ErrorCode = "forbidden"
	IdempotencyConflict  ErrorCode = "idempotency_conflict"
	Internal             ErrorCode = "internal"
	Invalid              ErrorCode = "invalid"
	InvalidLimit         ErrorCode = "invalid_limit"
	InvalidMessage       ErrorCode = "invalid_message"
	InvalidProject       ErrorCode = "invalid_project"
	InvalidSettings      ErrorCode = "invalid_settings"
	InvalidWorkspace     ErrorCode = "invalid_workspace"
	MethodNotAllowed     ErrorCode = "method_not_allowed"
	NotFound             ErrorCode = "not_found"
	NotPending           ErrorCode = "not_pending"
	NotRunning           ErrorCode = "not_running"
	ProjectExists        ErrorCode = "project_exists"
	ProjectNotEmpty      ErrorCode = "project_not_empty"
	Settled              ErrorCode = "settled"
	ShuttingDown         ErrorCode = "shutting_down"
	StorageFailed        ErrorCode = "storage_failed"
	TooLarge             ErrorCode = "too_large"
	TurnRequired         ErrorCode = "turn_required"
	UnsupportedMediaType ErrorCode = "unsupported_media_type"
	WorkspaceFailed      ErrorCode = "workspace_failed"
	WorkspaceLocked      ErrorCode = "workspace_locked"
	WorkspaceUnavailable ErrorCode = "workspace_unavailable"
)

// Defines values for EventType.
const (
	AgentCreated     EventType = "agent.created"
	AgentUpdated     EventType = "agent.updated"
	Conversation     EventType = "conversation"
	MessageCancelled EventType = "message.cancelled"
	MessageQueued    EventType = "message.queued"
	Output           EventType = "output"
	TurnCancelled    EventType = "turn.cancelled"
	TurnCompleted    EventType = "turn.completed"
	TurnFailed       EventType = "turn.failed"
	TurnInterrupted  EventType = "turn.interrupted"
	TurnStarted      EventType = "turn.started"
)

// Defines values for HealthApiVersion.
const (
	N1 HealthApiVersion = "1"
)

// Defines values for QueuedMessageStatus.
const (
	QueuedMessageStatusCancelled   QueuedMessageStatus = "cancelled"
	QueuedMessageStatusCompleted   QueuedMessageStatus = "completed"
	QueuedMessageStatusFailed      QueuedMessageStatus = "failed"
	QueuedMessageStatusInterrupted QueuedMessageStatus = "interrupted"
	QueuedMessageStatusPending     QueuedMessageStatus = "pending"
	QueuedMessageStatusRunning     QueuedMessageStatus = "running"
)

// Defines values for WSAckType.
const (
	Ack WSAckType = "ack"
)

// Defines values for WSErrorType.
const (
	WSErrorTypeError WSErrorType = "error"
)

// Defines values for WSEventType.
const (
	WSEventTypeEvent WSEventType = "event"
)

// Defines values for WSEventReferenceType.
const (
	EventRef WSEventReferenceType = "event_ref"
)

// Defines values for WSInventoryType.
const (
	Inventory WSInventoryType = "inventory"
)

// Defines values for WSSubmitType.
const (
	Submit WSSubmitType = "submit"
)

// Defines values for WSSubscribeType.
const (
	Subscribe WSSubscribeType = "subscribe"
)

// Defines values for WSSubscribedType.
const (
	Subscribed WSSubscribedType = "subscribed"
)

// Defines values for WorkspaceMode.
const (
	WorkspaceModeCurrentCheckout WorkspaceMode = "current_checkout"
	WorkspaceModeWorktree        WorkspaceMode = "worktree"
)

// Defines values for WorkspaceStatus.
const (
	Creating WorkspaceStatus = "creating"
	Draft    WorkspaceStatus = "draft"
	Failed   WorkspaceStatus = "failed"
	Fetching WorkspaceStatus = "fetching"
	Ready    WorkspaceStatus = "ready"
)

// Defines values for WorkspaceSelectionMode.
const (
	WorkspaceSelectionModeCurrentCheckout WorkspaceSelectionMode = "current_checkout"
	WorkspaceSelectionModeWorktree        WorkspaceSelectionMode = "worktree"
)

// Agent defines model for Agent.
type Agent struct {
	ActiveSettings *Settings        `json:"active_settings,omitempty"`
	ContextUsage   *ContextUsage    `json:"context_usage,omitempty"`
	CreatedAt      time.Time        `json:"created_at"`
	Cursor         int64            `json:"cursor"`
	Held           bool             `json:"held"`
	Id             string           `json:"id"`
	Messages       *[]Message       `json:"messages,omitempty"`
	ProjectId      string           `json:"project_id"`
	Queue          *[]QueuedMessage `json:"queue,omitempty"`
	Settings       Settings         `json:"settings"`
	Settled        bool             `json:"settled"`
	State          AgentState       `json:"state"`
	Title          string           `json:"title"`
	UpdatedAt      time.Time        `json:"updated_at"`
	Workspace      *Workspace       `json:"workspace,omitempty"`
}

// AgentState defines model for Agent.State.
type AgentState string

// AgentOutput Retained agent.AgentResponse. PascalCase field names are intentional compatibility with the existing runtime output payload.
type AgentOutput struct {
	// Content Display/provider-context output, possibly capped for tool results.
	Content string `json:"Content"`

	// FullToolOutput Complete uncapped tool stdout/stderr including cancellation/failure annotations; empty on non-tool-result output.
	FullToolOutput string                  `json:"FullToolOutput"`
	ResponseType   AgentOutputResponseType `json:"ResponseType"`
	ToolCallID     string                  `json:"ToolCallID"`
	ToolName       string                  `json:"ToolName"`
}

// AgentOutputResponseType defines model for AgentOutput.ResponseType.
type AgentOutputResponseType string

// AgentSummary defines model for AgentSummary.
type AgentSummary struct {
	ActiveSettings *Settings         `json:"active_settings,omitempty"`
	ContextUsage   *ContextUsage     `json:"context_usage,omitempty"`
	CreatedAt      time.Time         `json:"created_at"`
	Cursor         int64             `json:"cursor"`
	Held           bool              `json:"held"`
	Id             string            `json:"id"`
	ProjectId      string            `json:"project_id"`
	Settings       Settings          `json:"settings"`
	Settled        bool              `json:"settled"`
	State          AgentSummaryState `json:"state"`
	Title          string            `json:"title"`
	UpdatedAt      time.Time         `json:"updated_at"`
	Workspace      *Workspace        `json:"workspace,omitempty"`
}

// AgentSummaryState defines model for AgentSummary.State.
type AgentSummaryState string

// AgentUpdate State payload for agent.created and agent.updated. The enclosing Event supplies agent_id, cursor and created_at. This is not a complete Agent resource; it deliberately excludes history and queue.
type AgentUpdate struct {
	ActiveSettings *NullableSettings `json:"active_settings"`
	ContextUsage   ContextUsage      `json:"context_usage"`
	Held           bool              `json:"held"`
	Id             string            `json:"id"`
	ProjectId      string            `json:"project_id"`
	Settings       Settings          `json:"settings"`
	Settled        bool              `json:"settled"`
	State          AgentUpdateState  `json:"state"`
	Title          string            `json:"title"`
	Workspace      *Workspace        `json:"workspace,omitempty"`
}

// AgentUpdateState defines model for AgentUpdate.State.
type AgentUpdateState string

// ContentPart defines model for ContentPart.
type ContentPart struct {
	ImageUrl             *ContentPart_ImageUrl  `json:"image_url,omitempty"`
	Text                 *string                `json:"text,omitempty"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContentPartImageUrl1 defines model for .
type ContentPartImageUrl1 = string

// ContentPart_ImageUrl defines model for ContentPart.ImageUrl.
type ContentPart_ImageUrl struct {
	union json.RawMessage
}

// ContextUsage defines model for ContextUsage.
type ContextUsage struct {
	ContextWindow   int64  `json:"context_window"`
	Estimated       bool   `json:"estimated"`
	EstimatedTokens int64  `json:"estimated_tokens"`
	InputTokens     int64  `json:"input_tokens"`
	Known           bool   `json:"known"`
	Model           string `json:"model"`
	OutputTokens    int64  `json:"output_tokens"`
}

// ConversationDelta New committed messages appended since the previous conversation event, not a full conversation snapshot.
type ConversationDelta = []Message

// CreateAgentRequest defines model for CreateAgentRequest.
type CreateAgentRequest struct {
	ProjectId string              `json:"project_id"`
	Prompt    *string             `json:"prompt,omitempty"`
	Settings  *SettingsPatch      `json:"settings,omitempty"`
	Title     *string             `json:"title,omitempty"`
	Workspace *WorkspaceSelection `json:"workspace,omitempty"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Defaults          Settings            `json:"defaults"`
	Name              string              `json:"name"`
	Root              string              `json:"root"`
	WorkspaceDefaults *WorkspaceSelection `json:"workspace_defaults,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    ErrorCode `json:"code"`
		Message string    `json:"message"`
	} `json:"error"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Event defines model for Event.
type Event struct {
	AgentId   string    `json:"agent_id"`
	CreatedAt time.Time `json:"created_at"`
	Cursor    int64     `json:"cursor"`

	// Data Payload selected by Event.type; see x-event-data-schemas on Event and websocket.md.
	Data EventData `json:"data"`
	Type EventType `json:"type"`
}

// EventType defines model for Event.Type.
type EventType string

// EventData Payload selected by Event.type; see x-event-data-schemas on Event and websocket.md.
type EventData struct {
	union json.RawMessage
}

// EventPage defines model for EventPage.
type EventPage struct {
	Events     []Event `json:"events"`
	NextCursor int64   `json:"next_cursor"`
}

// FunctionCall defines model for FunctionCall.
type FunctionCall struct {
	// Arguments JSON-encoded function arguments.
	Arguments string `json:"arguments"`
	Name      string `json:"name"`
}

// Health defines model for Health.
type Health struct {
	ApiVersion HealthApiVersion `json:"api_version"`
}

// HealthApiVersion defines model for Health.ApiVersion.
type HealthApiVersion string

// HistoryPage defines model for HistoryPage.
type HistoryPage struct {
	Messages   []Message `json:"messages"`
	NextCursor int64     `json:"next_cursor"`
}

// ImageURL defines model for ImageURL.
type ImageURL struct {
	Detail               *string                `json:"detail,omitempty"`
	Url                  string                 `json:"url"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Message Provider-neutral retained conversation message, including reasoning provenance and tool results. Unknown provider fields are preserved.
type Message struct {
	// Content Original provider body: plain text, typed multimodal parts, or null. Replayed without normalization.
	Content          *MessageContent    `json:"content"`
	Reasoning        *string            `json:"reasoning,omitempty"`
	ReasoningDetails *[]ReasoningDetail `json:"reasoning_details,omitempty"`
	Role             string             `json:"role"`

	// SourceModel Origin model for opaque reasoning replay; not forwarded as a provider message field.
	SourceModel          *string                `json:"source_model,omitempty"`
	ToolCallId           *string                `json:"tool_call_id,omitempty"`
	ToolCalls            *[]ToolCall            `json:"tool_calls,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MessageContent Original provider body: plain text, typed multimodal parts, or null. Replayed without normalization.
type MessageContent struct {
	union json.RawMessage
}

// MessageContent0 defines model for .
type MessageContent0 = string

// MessageContent1 defines model for .
type MessageContent1 = []ContentPart

// Model defines model for Model.
type Model struct {
	ContextWindow int64    `json:"context_window"`
	DefaultEffort string   `json:"default_effort"`
	Efforts       []string `json:"efforts"`
	Id            string   `json:"id"`
	Name          string   `json:"name"`
	Provider      string   `json:"provider"`
}

// NullableSettings defines model for NullableSettings.
type NullableSettings struct {
	Effort string `json:"effort"`
	Model  string `json:"model"`
}

// PatchAgentRequest defines model for PatchAgentRequest.
type PatchAgentRequest struct {
	Settled bool `json:"settled"`
}

// PatchProjectRequest defines model for PatchProjectRequest.
type PatchProjectRequest struct {
	Defaults          *Settings           `json:"defaults,omitempty"`
	Name              *string             `json:"name,omitempty"`
	WorkspaceDefaults *WorkspaceSelection `json:"workspace_defaults,omitempty"`
}

// Project defines model for Project.
type Project struct {
	Defaults Settings `json:"defaults"`

	// GitBranch Live server-side Git branch (or detached commit), populated on GET project; omitted outside Git repositories.
	GitBranch         *string             `json:"git_branch,omitempty"`
	Id                string              `json:"id"`
	Name              string              `json:"name"`
	Root              string              `json:"root"`
	WorkspaceDefaults *WorkspaceSelection `json:"workspace_defaults,omitempty"`
}

// ProjectBranches defines model for ProjectBranches.
type ProjectBranches struct {
	Branches      []string `json:"branches"`
	DefaultBranch string   `json:"default_branch"`
	IsGit         bool     `json:"is_git"`
}

// QueuedMessage defines model for QueuedMessage.
type QueuedMessage struct {
	CreatedAt time.Time           `json:"created_at"`
	Error     *string             `json:"error,omitempty"`
	Id        string              `json:"id"`
	Status    QueuedMessageStatus `json:"status"`
	Text      string              `json:"text"`
}

// QueuedMessageStatus defines model for QueuedMessage.Status.
type QueuedMessageStatus string

// ReasoningDetail Opaque extended thinking record. Unknown provider fields, encrypted data and signatures must be preserved unchanged.
type ReasoningDetail struct {
	Data                 *json.RawMessage       `json:"data"`
	Format               *string                `json:"format,omitempty"`
	Id                   *string                `json:"id,omitempty"`
	Index                *int64                 `json:"index,omitempty"`
	Signature            *string                `json:"signature,omitempty"`
	Summary              *json.RawMessage       `json:"summary"`
	Text                 *string                `json:"text,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Settings defines model for Settings.
type Settings struct {
	Effort string `json:"effort"`
	Model  string `json:"model"`
}

// SettingsPatch defines model for SettingsPatch.
type SettingsPatch struct {
	Effort *string `json:"effort,omitempty"`
	Model  *string `json:"model,omitempty"`
}

// StopRequest defines model for StopRequest.
type StopRequest struct {
	TurnId string `json:"turn_id"`
}

// SubmitMessageRequest defines model for SubmitMessageRequest.
type SubmitMessageRequest struct {
	Text string `json:"text"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	Function FunctionCall `json:"function"`
	Id       string       `json:"id"`
	Index    int64        `json:"index"`
	Type     string       `json:"type"`
}

// WSAck defines model for WSAck.
type WSAck struct {
	AgentId   string    `json:"agent_id"`
	MessageId string    `json:"message_id"`
	RequestId string    `json:"request_id"`
	Status    string    `json:"status"`
	Type      WSAckType `json:"type"`
}

// WSAckType defines model for WSAck.Type.
type WSAckType string

// WSError defines model for WSError.
type WSError struct {
	Code      ErrorCode   `json:"code"`
	Message   string      `json:"message"`
	RequestId *string     `json:"request_id,omitempty"`
	Type      WSErrorType `json:"type"`
}

// WSErrorType defines model for WSError.Type.
type WSErrorType string

// WSEvent defines model for WSEvent.
type WSEvent struct {
	Event Event       `json:"event"`
	Type  WSEventType `json:"type"`
}

// WSEventType defines model for WSEvent.Type.
type WSEventType string

// WSEventReference defines model for WSEventReference.
type WSEventReference struct {
	AgentId string               `json:"agent_id"`
	Cursor  int64                `json:"cursor"`
	Type    WSEventReferenceType `json:"type"`
	Url     string               `json:"url"`
}

// WSEventReferenceType defines model for WSEventReference.Type.
type WSEventReferenceType string

// WSInventory defines model for WSInventory.
type WSInventory struct {
	Agent AgentSummary    `json:"agent"`
	Type  WSInventoryType `json:"type"`
}

// WSInventoryType defines model for WSInventory.Type.
type WSInventoryType string

// WSSubmit defines model for WSSubmit.
type WSSubmit struct {
	AgentId        string       `json:"agent_id"`
	IdempotencyKey string       `json:"idempotency_key"`
	RequestId      string       `json:"request_id"`
	Text           string       `json:"text"`
	Type           WSSubmitType `json:"type"`
}

// WSSubmitType defines model for WSSubmit.Type.
type WSSubmitType string

// WSSubscribe defines model for WSSubscribe.
type WSSubscribe struct {
	AgentIds     *[]string         `json:"agent_ids,omitempty"`
	Cursors      *map[string]int64 `json:"cursors,omitempty"`
	RequestId    string            `json:"request_id"`
	SubscribeAll *bool             `json:"subscribe_all,omitempty"`
	Type         WSSubscribeType   `json:"type"`
}

// WSSubscribeType defines model for WSSubscribe.Type.
type WSSubscribeType string

// WSSubscribed defines model for WSSubscribed.
type WSSubscribed struct {
	RequestId string           `json:"request_id"`
	Type      WSSubscribedType `json:"type"`
}

// WSSubscribedType defines model for WSSubscribed.Type.
type WSSubscribedType string

// Workspace defines model for Workspace.
type Workspace struct {
	BaseBranch *string         `json:"base_branch,omitempty"`
	BaseCommit *string         `json:"base_commit,omitempty"`
	Branch     *string         `json:"branch,omitempty"`
	Error      *string         `json:"error,omitempty"`
	Locked     bool            `json:"locked"`
	Mode       WorkspaceMode   `json:"mode"`
	Path       *string         `json:"path,omitempty"`
	Status     WorkspaceStatus `json:"status"`
}

// WorkspaceMode defines model for Workspace.Mode.
type WorkspaceMode string

// WorkspaceStatus defines model for Workspace.Status.
type WorkspaceStatus string

// WorkspaceSelection defines model for WorkspaceSelection.
type WorkspaceSelection struct {
	BaseBranch *string                `json:"base_branch,omitempty"`
	Mode       WorkspaceSelectionMode `json:"mode"`
}

// WorkspaceSelectionMode defines model for WorkspaceSelection.Mode.
type WorkspaceSelectionMode string

// ListAgentsParams defines parameters for ListAgents.
type ListAgentsParams struct {
	IncludeSettled *bool   `form:"include_settled,omitempty" json:"include_settled,omitempty"`
	ProjectId      *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// CreateAgentParams defines parameters for CreateAgent.
type CreateAgentParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	After *int64 `form:"after,omitempty" json:"after,omitempty"`
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetHistoryParams defines parameters for GetHistory.
type GetHistoryParams struct {
	After *int64 `form:"after,omitempty" json:"after,omitempty"`
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// SubmitMessageParams defines parameters for SubmitMessage.
type SubmitMessageParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = CreateAgentRequest

// PatchAgentJSONRequestBody defines body for PatchAgent for application/json ContentType.
type PatchAgentJSONRequestBody = PatchAgentRequest

// SubmitMessageJSONRequestBody defines body for SubmitMessage for application/json ContentType.
type SubmitMessageJSONRequestBody = SubmitMessageRequest

// PatchAgentSettingsJSONRequestBody defines body for PatchAgentSettings for application/json ContentType.
type PatchAgentSettingsJSONRequestBody = SettingsPatch

// StopAgentJSONRequestBody defines body for StopAgent for application/json ContentType.
type StopAgentJSONRequestBody = StopRequest

// PatchAgentWorkspaceJSONRequestBody defines body for PatchAgentWorkspace for application/json ContentType.
type PatchAgentWorkspaceJSONRequestBody = WorkspaceSelection

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// PatchProjectJSONRequestBody defines body for PatchProject for application/json ContentType.
type PatchProjectJSONRequestBody = PatchProjectRequest

// Getter for additional properties for ContentPart. Returns the specified
// element and whether it was found
func (a ContentPart) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContentPart
func (a *ContentPart) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContentPart to handle AdditionalProperties
func (a *ContentPart) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["image_url"]; found {
		err = json.Unmarshal(raw, &a.ImageUrl)
		if err != nil {
			return fmt.Errorf("error reading 'image_url': %w", err)
		}
		delete(object, "image_url")
	}

	if raw, found := object["text"]; found {
		err = json.Unmarshal(raw, &a.Text)
		if err != nil {
			return fmt.Errorf("error reading 'text': %w", err)
		}
		delete(object, "text")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContentPart to handle AdditionalProperties
func (a ContentPart) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ImageUrl != nil {
		object["image_url"], err = json.Marshal(a.ImageUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'image_url': %w", err)
		}
	}

	if a.Text != nil {
		object["text"], err = json.Marshal(a.Text)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'text': %w", err)
		}
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ImageURL. Returns the specified
// element and whether it was found
func (a ImageURL) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ImageURL
func (a *ImageURL) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ImageURL to handle AdditionalProperties
func (a *ImageURL) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &a.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
		delete(object, "url")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ImageURL to handle AdditionalProperties
func (a ImageURL) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["url"], err = json.Marshal(a.Url)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'url': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Message. Returns the specified
// element and whether it was found
func (a Message) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Message
func (a *Message) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Message to handle AdditionalProperties
func (a *Message) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return fmt.Errorf("error reading 'content': %w", err)
		}
		delete(object, "content")
	}

	if raw, found := object["reasoning"]; found {
		err = json.Unmarshal(raw, &a.Reasoning)
		if err != nil {
			return fmt.Errorf("error reading 'reasoning': %w", err)
		}
		delete(object, "reasoning")
	}

	if raw, found := object["reasoning_details"]; found {
		err = json.Unmarshal(raw, &a.ReasoningDetails)
		if err != nil {
			return fmt.Errorf("error reading 'reasoning_details': %w", err)
		}
		delete(object, "reasoning_details")
	}

	if raw, found := object["role"]; found {
		err = json.Unmarshal(raw, &a.Role)
		if err != nil {
			return fmt.Errorf("error reading 'role': %w", err)
		}
		delete(object, "role")
	}

	if raw, found := object["source_model"]; found {
		err = json.Unmarshal(raw, &a.SourceModel)
		if err != nil {
			return fmt.Errorf("error reading 'source_model': %w", err)
		}
		delete(object, "source_model")
	}

	if raw, found := object["tool_call_id"]; found {
		err = json.Unmarshal(raw, &a.ToolCallId)
		if err != nil {
			return fmt.Errorf("error reading 'tool_call_id': %w", err)
		}
		delete(object, "tool_call_id")
	}

	if raw, found := object["tool_calls"]; found {
		err = json.Unmarshal(raw, &a.ToolCalls)
		if err != nil {
			return fmt.Errorf("error reading 'tool_calls': %w", err)
		}
		delete(object, "tool_calls")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Message to handle AdditionalProperties
func (a Message) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["content"], err = json.Marshal(a.Content)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'content': %w", err)
	}

	if a.Reasoning != nil {
		object["reasoning"], err = json.Marshal(a.Reasoning)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reasoning': %w", err)
		}
	}

	if a.ReasoningDetails != nil {
		object["reasoning_details"], err = json.Marshal(a.ReasoningDetails)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reasoning_details': %w", err)
		}
	}

	object["role"], err = json.Marshal(a.Role)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'role': %w", err)
	}

	if a.SourceModel != nil {
		object["source_model"], err = json.Marshal(a.SourceModel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'source_model': %w", err)
		}
	}

	if a.ToolCallId != nil {
		object["tool_call_id"], err = json.Marshal(a.ToolCallId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tool_call_id': %w", err)
		}
	}

	if a.ToolCalls != nil {
		object["tool_calls"], err = json.Marshal(a.ToolCalls)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tool_calls': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ReasoningDetail. Returns the specified
// element and whether it was found
func (a ReasoningDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ReasoningDetail
func (a *ReasoningDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ReasoningDetail to handle AdditionalProperties
func (a *ReasoningDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["data"]; found {
		err = json.Unmarshal(raw, &a.Data)
		if err != nil {
			return fmt.Errorf("error reading 'data': %w", err)
		}
		delete(object, "data")
	}

	if raw, found := object["format"]; found {
		err = json.Unmarshal(raw, &a.Format)
		if err != nil {
			return fmt.Errorf("error reading 'format': %w", err)
		}
		delete(object, "format")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["index"]; found {
		err = json.Unmarshal(raw, &a.Index)
		if err != nil {
			return fmt.Errorf("error reading 'index': %w", err)
		}
		delete(object, "index")
	}

	if raw, found := object["signature"]; found {
		err = json.Unmarshal(raw, &a.Signature)
		if err != nil {
			return fmt.Errorf("error reading 'signature': %w", err)
		}
		delete(object, "signature")
	}

	if raw, found := object["summary"]; found {
		err = json.Unmarshal(raw, &a.Summary)
		if err != nil {
			return fmt.Errorf("error reading 'summary': %w", err)
		}
		delete(object, "summary")
	}

	if raw, found := object["text"]; found {
		err = json.Unmarshal(raw, &a.Text)
		if err != nil {
			return fmt.Errorf("error reading 'text': %w", err)
		}
		delete(object, "text")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ReasoningDetail to handle AdditionalProperties
func (a ReasoningDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Data != nil {
		object["data"], err = json.Marshal(a.Data)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'data': %w", err)
		}
	}

	if a.Format != nil {
		object["format"], err = json.Marshal(a.Format)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'format': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Index != nil {
		object["index"], err = json.Marshal(a.Index)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'index': %w", err)
		}
	}

	if a.Signature != nil {
		object["signature"], err = json.Marshal(a.Signature)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'signature': %w", err)
		}
	}

	if a.Summary != nil {
		object["summary"], err = json.Marshal(a.Summary)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'summary': %w", err)
		}
	}

	if a.Text != nil {
		object["text"], err = json.Marshal(a.Text)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'text': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsImageURL returns the union data inside the ContentPart_ImageUrl as a ImageURL
func (t ContentPart_ImageUrl) AsImageURL() (ImageURL, error) {
	var body ImageURL
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURL overwrites any union data inside the ContentPart_ImageUrl as the provided ImageURL
func (t *ContentPart_ImageUrl) FromImageURL(v ImageURL) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURL performs a merge with any union data inside the ContentPart_ImageUrl, using the provided ImageURL
func (t *ContentPart_ImageUrl) MergeImageURL(v ImageURL) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentPartImageUrl1 returns the union data inside the ContentPart_ImageUrl as a ContentPartImageUrl1
func (t ContentPart_ImageUrl) AsContentPartImageUrl1() (ContentPartImageUrl1, error) {
	var body ContentPartImageUrl1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentPartImageUrl1 overwrites any union data inside the ContentPart_ImageUrl as the provided ContentPartImageUrl1
func (t *ContentPart_ImageUrl) FromContentPartImageUrl1(v ContentPartImageUrl1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentPartImageUrl1 performs a merge with any union data inside the ContentPart_ImageUrl, using the provided ContentPartImageUrl1
func (t *ContentPart_ImageUrl) MergeContentPartImageUrl1(v ContentPartImageUrl1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart_ImageUrl) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart_ImageUrl) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAgentUpdate returns the union data inside the EventData as a AgentUpdate
func (t EventData) AsAgentUpdate() (AgentUpdate, error) {
	var body AgentUpdate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentUpdate overwrites any union data inside the EventData as the provided AgentUpdate
func (t *EventData) FromAgentUpdate(v AgentUpdate) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentUpdate performs a merge with any union data inside the EventData, using the provided AgentUpdate
func (t *EventData) MergeAgentUpdate(v AgentUpdate) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQueuedMessage returns the union data inside the EventData as a QueuedMessage
func (t EventData) AsQueuedMessage() (QueuedMessage, error) {
	var body QueuedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueuedMessage overwrites any union data inside the EventData as the provided QueuedMessage
func (t *EventData) FromQueuedMessage(v QueuedMessage) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueuedMessage performs a merge with any union data inside the EventData, using the provided QueuedMessage
func (t *EventData) MergeQueuedMessage(v QueuedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentOutput returns the union data inside the EventData as a AgentOutput
func (t EventData) AsAgentOutput() (AgentOutput, error) {
	var body AgentOutput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentOutput overwrites any union data inside the EventData as the provided AgentOutput
func (t *EventData) FromAgentOutput(v AgentOutput) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentOutput performs a merge with any union data inside the EventData, using the provided AgentOutput
func (t *EventData) MergeAgentOutput(v AgentOutput) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConversationDelta returns the union data inside the EventData as a ConversationDelta
func (t EventData) AsConversationDelta() (ConversationDelta, error) {
	var body ConversationDelta
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConversationDelta overwrites any union data inside the EventData as the provided ConversationDelta
func (t *EventData) FromConversationDelta(v ConversationDelta) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConversationDelta performs a merge with any union data inside the EventData, using the provided ConversationDelta
func (t *EventData) MergeConversationDelta(v ConversationDelta) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventData) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventData) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMessageContent0 returns the union data inside the MessageContent as a MessageContent0
func (t MessageContent) AsMessageContent0() (MessageContent0, error) {
	var body MessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageContent0 overwrites any union data inside the MessageContent as the provided MessageContent0
func (t *MessageContent) FromMessageContent0(v MessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageContent0 performs a merge with any union data inside the MessageContent, using the provided MessageContent0
func (t *MessageContent) MergeMessageContent0(v MessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageContent1 returns the union data inside the MessageContent as a MessageContent1
func (t MessageContent) AsMessageContent1() (MessageContent1, error) {
	var body MessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageContent1 overwrites any union data inside the MessageContent as the provided MessageContent1
func (t *MessageContent) FromMessageContent1(v MessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageContent1 performs a merge with any union data inside the MessageContent, using the provided MessageContent1
func (t *MessageContent) MergeMessageContent1(v MessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MessageContent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MessageContent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /v1/agents)
	ListAgents(w http.ResponseWriter, r *http.Request, params ListAgentsParams)

	// (POST /v1/agents)
	CreateAgent(w http.ResponseWriter, r *http.Request, params CreateAgentParams)

	// (GET /v1/agents/{agent_id})
	GetAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (PATCH /v1/agents/{agent_id})
	PatchAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (POST /v1/agents/{agent_id}/continue)
	ContinueAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (GET /v1/agents/{agent_id}/events)
	GetEvents(w http.ResponseWriter, r *http.Request, agentId string, params GetEventsParams)

	// (GET /v1/agents/{agent_id}/events/{cursor})
	GetEvent(w http.ResponseWriter, r *http.Request, agentId string, cursor int64)

	// (GET /v1/agents/{agent_id}/history)
	GetHistory(w http.ResponseWriter, r *http.Request, agentId string, params GetHistoryParams)

	// (GET /v1/agents/{agent_id}/messages)
	ListMessages(w http.ResponseWriter, r *http.Request, agentId string)

	// (POST /v1/agents/{agent_id}/messages)
	SubmitMessage(w http.ResponseWriter, r *http.Request, agentId string, params SubmitMessageParams)

	// (DELETE /v1/agents/{agent_id}/messages/{message_id})
	DeletePending(w http.ResponseWriter, r *http.Request, agentId string, messageId string)

	// (PATCH /v1/agents/{agent_id}/settings)
	PatchAgentSettings(w http.ResponseWriter, r *http.Request, agentId string)

	// (POST /v1/agents/{agent_id}/stop)
	StopAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (PATCH /v1/agents/{agent_id}/workspace)
	PatchAgentWorkspace(w http.ResponseWriter, r *http.Request, agentId string)

	// (GET /v1/models)
	ListModels(w http.ResponseWriter, r *http.Request)

	// (GET /v1/projects)
	ListProjects(w http.ResponseWriter, r *http.Request)

	// (POST /v1/projects)
	CreateProject(w http.ResponseWriter, r *http.Request)

	// (DELETE /v1/projects/{project_id})
	DeleteProject(w http.ResponseWriter, r *http.Request, projectId string)

	// (GET /v1/projects/{project_id})
	GetProject(w http.ResponseWriter, r *http.Request, projectId string)

	// (PATCH /v1/projects/{project_id})
	PatchProject(w http.ResponseWriter, r *http.Request, projectId string)

	// (GET /v1/projects/{project_id}/branches)
	ListProjectBranches(w http.ResponseWriter, r *http.Request, projectId string)

	// (GET /v1/ws)
	WebSocket(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentsParams

	// ------------- Optional query parameter "include_settled" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_settled", r.URL.Query(), &params.IncludeSettled)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_settled", Err: err})
		return
	}

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAgent operation middleware
func (siw *ServerInterfaceWrapper) CreateAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateAgentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgent operation middleware
func (siw *ServerInterfaceWrapper) GetAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAgent operation middleware
func (siw *ServerInterfaceWrapper) PatchAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ContinueAgent operation middleware
func (siw *ServerInterfaceWrapper) ContinueAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ContinueAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// ------------- Path parameter "cursor" -------------
	var cursor int64

	err = runtime.BindStyledParameterWithOptions("simple", "cursor", r.PathValue("cursor"), &cursor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, agentId, cursor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHistory operation middleware
func (siw *ServerInterfaceWrapper) GetHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHistoryParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHistory(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitMessage operation middleware
func (siw *ServerInterfaceWrapper) SubmitMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SubmitMessageParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitMessage(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePending operation middleware
func (siw *ServerInterfaceWrapper) DeletePending(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// ------------- Path parameter "message_id" -------------
	var messageId string

	err = runtime.BindStyledParameterWithOptions("simple", "message_id", r.PathValue("message_id"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "message_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePending(w, r, agentId, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAgentSettings operation middleware
func (siw *ServerInterfaceWrapper) PatchAgentSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAgentSettings(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopAgent operation middleware
func (siw *ServerInterfaceWrapper) StopAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAgentWorkspace operation middleware
func (siw *ServerInterfaceWrapper) PatchAgentWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAgentWorkspace(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchProject operation middleware
func (siw *ServerInterfaceWrapper) PatchProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectBranches operation middleware
func (siw *ServerInterfaceWrapper) ListProjectBranches(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectBranches(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WebSocket operation middleware
func (siw *ServerInterfaceWrapper) WebSocket(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WebSocket(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents", wrapper.ListAgents)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents", wrapper.CreateAgent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}", wrapper.GetAgent)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/agents/{agent_id}", wrapper.PatchAgent)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents/{agent_id}/continue", wrapper.ContinueAgent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/events", wrapper.GetEvents)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/events/{cursor}", wrapper.GetEvent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/history", wrapper.GetHistory)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/messages", wrapper.ListMessages)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents/{agent_id}/messages", wrapper.SubmitMessage)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/agents/{agent_id}/messages/{message_id}", wrapper.DeletePending)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/agents/{agent_id}/settings", wrapper.PatchAgentSettings)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents/{agent_id}/stop", wrapper.StopAgent)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/agents/{agent_id}/workspace", wrapper.PatchAgentWorkspace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/models", wrapper.ListModels)
	m.HandleFunc("GET "+options.BaseURL+"/v1/projects", wrapper.ListProjects)
	m.HandleFunc("POST "+options.BaseURL+"/v1/projects", wrapper.CreateProject)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/projects/{project_id}", wrapper.DeleteProject)
	m.HandleFunc("GET "+options.BaseURL+"/v1/projects/{project_id}", wrapper.GetProject)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/projects/{project_id}", wrapper.PatchProject)
	m.HandleFunc("GET "+options.BaseURL+"/v1/projects/{project_id}/branches", wrapper.ListProjectBranches)
	m.HandleFunc("GET "+options.BaseURL+"/v1/ws", wrapper.WebSocket)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9WXMbt7L/V+ni//+QVFGUlCi5N9KTLTs5Oje2dCW7/HAqxQJnmiQiDDAGMKQYl777",
	"LSyzEly1WHHwJHEGwDQaDfx6A/Cll4gsFxy5Vr3TLz2VTDEj9t9XE+Ta/EPSlGoqOGFXUuQoNUXVOx0T",
	"prDfyxuPvvRIoukMhwq1pnxiH/1/iePeae//HdYfOvRfObwpy933e4ngGu/0sFBkgpsqnrvCH21ZU1ki",
	"0ZgOiSV4LGRm/uulROOBphn2+j29yLF32lNaUj6xdQqphGyVp1z/fNLr9zLKaVZkvdOjqh7lGicoTcUp",
	"stRU829GQjAk3Lyh9nlG7n5HPtHT3ukPP/1sWyt/HwfoyFCZblhmUY3ZRq69cxVMXd8YkZIszO9cij8x",
	"0cO9CPlcYIFbU/G/pnS6hpZ9hMDUYbiCu0oTbelDbsbmPz2aMjOysuDcdMGUEHlu/v0j0D1NNcNGy/Wb",
	"Ik93lp65kLcqJ8lGUf1UFby/7/ckfi6oND005PdaI1aS2GBdzZGy+178KvFtyX6rKzUPxMh8wlBt5/Rl",
	"ofNi88xOUSWS5uZ977R3jZpQjikQ08TANnSNKhdc4QCuiEoIOycKYUyRpcBJhgqIRDATh7uPgGEP0XRE",
	"GdULmFM9BT1FwDuqTH9BFtzwG4SlEHKyYIKkg153mbHT3y1ObSrfUJUzsjjMpZjRFOWBX1V8i33IhVJ0",
	"xBaQkDzHFMZCghaCgURVMK0GobH+tWDsgxCsZlz7q+ciyxlqhIL7Zm2TSqei0IdKpyglUJ6wIjW9TAhP",
	"kDFiah+OCWWFRCCcC20fqTPALNcLEBy44AemrQNHnu9GkMhyMD7YF/UkseNlKgjB/J+ha83LVGHEzK26",
	"oWljOn5OGLt4E5w75vV7koUmVkfcy0HrkNr6QqO9JbavlOebIsuIXESoenKoehC8RDx4oXjw0ZbZEQ9u",
	"zNfLFdouow4Y/NeB8BIqPAkD+GCWep4wocwq+HaGXIMq8pxRAxWm7JCmfXAdsQ3UXTG1qQKqgAsNxCKJ",
	"XXJtD8zqLQqZ4BlQDSkyOkJJNLIF4J1ZdlHBlCot5MK2azWdZVjZcUl4XzBGRgwfbWmIs3Wf2fpcM68r",
	"HevmYksKQhPPg+EVkWsUMS2LJdiiGZngsJDM/BAcL8e90/+s7/eFqfLx+vfefX+JfX8Y1uKdDnJWe1Vi",
	"Pa7btyv7WIr3buBcMnBOeSrmQeBbBjtUmmZmvQgLYPV6qMUtcrVlq5Tnhd6tyi0Xcx4mIhMpsiCznWq3",
	"y4c64+Ca7hDcbTfAhn6X22UHmhxdMb4zlMoqrW+QabKsGb/HuVmqM6oNJpSWLhglmaeYgqI8QWsD5BJn",
	"VBQKkkargAYk+n7NHxeMtV8rTnI1FVYhfqjpfG6xxts1nwtUu/o+HrTc5lJkue5UPD46+e+f/uvx1+or",
	"opNpa1HtUvsIi+wNMkysGHQFtcGooFjZgbhyhfYbihTHxFhzu4AX90bMjgMnhegO28nRL5vrVQwdbkvs",
	"FpzlznCyNPVrLoS4/FZKZ1HswFbco04i0o0yY2k5NwVrd9hm3LEt1+WXO9kp76hfyYtzT2ilnvAZYVYX",
	"8P8Nvdw2njR0gfJRPVGaY8xEcmsVhfqRMfw7jwpOZoRanbLRYtnB+gmjGbUmfSH5sOpiv8eFHo5Fwb0K",
	"MmbUUlvON+tmUY0Hprx1NZi2U8xyoZEni2Gjrili1mqnoZlfDX2tUn+cyj6sWaamheXMMHVAYlRvo7dU",
	"nTYgJjlhdgD1VKSWGMKYmNv3WoghI9J2u+DGShDSYFaGKSVD7RwHYyFHNE2RBzVGa2Ds6hTwVsgeC8FT",
	"2fXHIQ0jJQ5t184q0/83pmBDlWt5hUpjzSi3TVOtnlUDayk1H3jnlRukQvKB0kTq+mdpmFUPqiG3v+y4",
	"yyJv1mi06JQVJ74VzAdGtzO1q2FrmMFeRiynWqOztAL0e3cHVtE4MIUPGiGQNpdW8LlpQ3cZuVWVVl9X",
	"m4odXSs0JFu56pcGd8tafmzWdemyHL7OwG75hY4A7VLLS9kuVZqiuEu9UuC3i4uUC9EbEtKPr7z/RFlI",
	"xxRGC+cYGRgRPQOFCCHhBMG9A4XwFOY4UgZg9CCzzvLtzMKmEBrLcJdgzxYte1nYVHZZsK1Najt3tbvh",
	"aFm1fSjNYUTAGuDGHtrT7drVOxxJ7TZDasivBbdq3TlhbFfckpMiK3veFrF/31y+P0ButKUUxv4TUFUI",
	"xhL4Vg59r23W3w516l9ImIHM3bqT06GRCtuDGrSOt0CCRs0gOc4LuIdkPWaY9hGlqyJrs3xVfqCdHE4p",
	"akLDLgvvhVo/IqZQiJp3tZ6/jpjOelnG9TgWWhIGsgxLtvwCnin9RtBNIlHCKK6QSzFDbrDJLp6t6B98",
	"5Nb3AWUA0YUzXSQzl6hQzjAQkEzqgOQWIlFGwiynPFlBBldvh24Uthe+67LmGzd8ASGUYoVD1bnSh5Wr",
	"qj0El5JOKAf71vr9RU4+F9hgsMSckcWZ9dqMhZwTaZYeooDUbPUj5NgbXINsoDIhjHl1fHWB7blSRhqX",
	"2dERWsubfjWsa+R3ZSja8Ymwus8jkS5OIWeEctB4p/tgGk0hK5immUhNWSK16oOQwAvGBnBtWYmpjZWL",
	"QgM3SwWjf1k5N3zjPghRzpca+7sM25JHTc/0EpsMNL8r5eJx/bnrA5nelzHE8VjIsLfavWoLwwqXdj0J",
	"VsjWCgC03bKDuXnds9aIh8iqVsDXWpK91MeQ0C2FnDYNQ1c8OtpSxc2GsfvzSShJqRz0naziFR7qNR20",
	"rskHOGHXhKA6xJQlV1Kxowcyo7z59Pgr+iQfzbe4zBjvAnt6d+yE6uFIEp5Ml5fW3+kMwUKxPFA0RfiN",
	"anCF4TshwYBlMrVKQZZR/X0fcpEXzMalBYff3n4A7wI7A+FjE6LQVVMSc6GoFpJiWD/ey0G0ck0pXcjP",
	"4yNurkvbOIr9kL+27EW149CPGtW2X5XLlbAWgOUhUMMJ1VvMc1+wX5Oy1H6o222Ld0e028MVWPnWH0fY",
	"fGJXw3iqvbi1B7fprGu7ZisXXe3ECUblw6HjkMjZoo2Ms3UeOZvO1lZgdzITLp1KinfahRn1lPJbp5om",
	"QqYr1fw+IE/kwnQdUqKJNRAUnXCiC4kKskJpGDUsASh4MiV8ErIJSh9tF4LvDibiwPf3TyX44JrMG7Zi",
	"KS4rJWH5MU/xbg+dqupY2Aqos+p27MEe+QRLw7+1gvPSFZp2zPWhSsQz9G+5B1rk+yljNj61x/LVTTDx",
	"zQTZW4wyqr3w7UmlF9edA+9dMk07IRorq3M3ukpf3SbMb7kNH3+V2C4JyC3xLuTivtSvOxBiyqebV8nt",
	"80XnvL9hv8rSydXwgUi8cj2sgnLJ7WYPp2dyg6Z+M/7V6Gj17TD/337daH6XrRu5043fr+fPxuwAy4I9",
	"QsQ428LR14krNDoxa/uT1neiW3qJ9msco0Se4DPGufeNWQdZMTRMDGmWW/mWPZtC4d9VbudPNxfcfFjs",
	"vmFgssXAtzYkBDpNq49vKwPus+GuOPR7vrFvJonc4uK5l9K9kXp5HJTj3ENX2y5D+qu1ADtaxkgZ7TtZ",
	"20b0rrzrmNhuoqzRr/dUFBo9fhhslswaes3J2+wVj5ZzawNj7Pm9xzBvGMJ0xzF8mNyv6lj6aD1rpnfu",
	"4t4hChtemtbE/OFkY8dsdeekC6oAa/w/q/0lPtduZfp1k5NJIaWZXMkUk1thU1fmQt5qieHNcDnRYXKW",
	"/S2pJGPT3hh1MvXuFolEex8MknRRe13+2MbS7FV9W6/ZLfsAn3VQH8bjUL8DqZ3WoBmLgG9YJIRBwUmh",
	"p8g1TazXNxFcS8EgZ4TjAF5TG/gFJkQ+IsktFJyhUpBLoas8HAJaFsr8yKW4WwzgFWPg5xE4QhRINH+h",
	"qP1JnpEDuHij3CYmt9LaEHIZK/X7XGlqSBxTlOqsVY4LznFCNJ25DbQTlGoAr0VKUYFN/7SbTOEHeEdf",
	"D+DfN5fvwc4IBWpqP8QRkM+QiRwH8F7AnLI0ITKF88vrm0G1w+W096HLHnh1ddHr96r8i97x4GhwZLco",
	"5MhJTnunvR8HR4Mfe24+WJk5nFZ5HhMMREN/Q+0zQWwz0sYvL9LOG+k3htomfzg66oTWSZ4zM6BU8MM/",
	"lZNrp3htUsv8F6zcdPaxFUmCyoYcTh7xg864CnzvwuXIloJ0WomOkJBRZbfGlc7IjDCDwZi6ARYSciJJ",
	"hhql6sNIFDxVMKPCbSVWA9eJk6fvhI8J9N2uvX6dbyGk27LhY/8FTz1RPz09Uf/68OEKXDKx2zDikok9",
	"Ab88PQHnPm3aDKHdENaHhn4It7gAiYXy0XxI6dgab9U+d8u+MjHC9MC77F0Pjp9BOM/d1kufxw3fkSmS",
	"FMS4TrNRWiLJDKFlwIzRMZrF7HtP5o9PT6b389mECsC7BDFVfil0NDyDtL29yx1SdNu2JPz0PEuJy6H3",
	"oVAHAP7zzzAKNyhnNEEoc/0h9ctYWkgyYgg+6R8a2xoGpqH7fu9wdnxo1w61EjF+p0q/mvjUyTZktF7V",
	"S6LNeqGm7ucC5aIMcxojxe4BHjb2a1Zd32RW2LyZQJut3aJ1c7v5uf94IORtldDjzvFZzniKUBihMEJh",
	"hMIIhV8PCvu9XKjQiUI2OQIId8vKGYjcH6HkNgq7EywUUK1gTKXSYLemwGVZ7KKebQf/gwvIyC0aa1VL",
	"Y0EqMsYzP+tsSrTfhlKdyKRIhn6WmoYVnBz9MljC4caW6RVAbCaNTXv0qNkh66HQaWX/tUgXjzbEgV3g",
	"922fhJYF3i/h9vGjUeDhOsJzhOcIzxGeIzy/FEv18EsZiLtf5+Ys4XDJy7kOJ21coULJRoCxjTtfz9KM",
	"iBURKyJWRKyIWC/eoCwTjbsnDZQbq5awqfXq66HT4xtzy5vJtrLlIjJGZIzIGJExIuM/wZY7NPRS7m4+",
	"CHtjr5EhUeicrjAVzB1vbGhNC4bljKnOt7QJN7IhLgHXqf9oNAoj9EXoi9AXoS9C3/NDX31a2ooUHCdp",
	"folhYtJ35+krOkMgY43SZ60OoHH4FFAFjCjtg4dYpsAaUl0lwf0VJzmZ4ADKJbrMgHX14OT4aAC/FoyB",
	"sMmof7ljGvJCmy+UM2QQ8rW+na3JDnpyXF2RMmT7Hk4+OurveghY+BPlybCBTxwfBT9C7vyWrSPzft0O",
	"ridVF+rz/qLKEFWGqDJElSGqDC9YZTj84rB6dST0V9TJ1G5Dqa7qqQTU3+pQH87oUV2Wu5nd/ht//cNQ",
	"4hg+4ejGHnELY7O6Wgvb19Ky4El1Hl5YFfjamkD7Q9Um5dWf2Wlv9dMjc0TliMoRlSMqR1R+majsL7db",
	"icbngdORlTfGCfyFUhyMiHI7QVWRYXpQzqaQfY+fC8LK6jkrVMPSFwXXA3hlxP9AjA/KW/eWTfuz9pHN",
	"9mpYdzZ5RhblRLJJ0CUNwa2jvuPR0v+7WPrNE9ijVhG1iqhVRK0iahUvUqtoXnkRVCsuuDJct1uGbHC8",
	"adRrlJk9AB+5Lk9SXt7H+66+v+JvGQPfagtu9/qcuBU3omBEwYiCEQVf/lZcu3YDKafAmj22KaaF6w8q",
	"sAcMKmVWQCCJFEqBXQoIT2tn9lljumm807tuwG2dfvy1beC/3V7f4NnRW2WI//BoNHRvC4yaQNQEoiYQ",
	"NYGoCbxge/jwS33K+r3TGBhqXNYd3tjnV9XNK2307r59QRHq1inyT2dqnyyzLOJdxLuIdxHvIt59fbxT",
	"jUuYVmwrPre3X0FZ0l4IOy50IdGeSKXOrDVLEnuSsQ393iLm7uCqhOSmYFrVHqzZmlxdCPVtbVFuXw8V",
	"tydHEI4gHEE4gnAE4QqEtchXb02+0SIHwdnC4qyBv9TB7Hf+1jygDmxteDatZtLFm+/PgKQzew1+uX/Z",
	"lhnADRkjaGFPi1xUN48bOnJTigDHOUp34uSyS1qL/Fs8S6R5C2KE6QjTEaYjTEeYjjBdwvS8eYPWemPZ",
	"IHVVHFR5SxOMcCyke+3OdOaCu23SVez5w7RZgYnkVgGVEmciISO2AMF9VYU8XWdO1xd+fVswHbwAP6J1",
	"ROuI1hGtI1r/M9Ha3oW//qahd65IMEO5fPX0ecL2UzE/OGJJxJKIJRFLXiKW+Hvf1qPJVVkohCeNl0+P",
	"KP5jEVMipkRMiZgSMeVvdP1buXaHr12r3z7dPWj+G1/pJrQKuyJWRayKWBWxKmLVy7F/Dr/UN2BvsQfC",
	"nubnjvx11QZwXe9shPmUMnTrkoIRMsEnoAVQPVi1a6JCv83Rq9ZV3XEzQ4SpCFMRpiJMfasm1aqLOVeZ",
	"U61XLwZNjqIZFfEp4lPEp4hP/4wLOj/m9rRTDy82ld+25071VGfVf0DGY1PCb7PzRpPgbLEi4e9loNsT",
	"Xe+5j4syYmvE1oitEVsjtv5zXJSHI0l4MsX1iRsgMRMaDz4XhNExxRR+oxrKqkCYRJIuwC2slNtcfSYS",
	"wiCZYnIrCm1vJuGo50LewthegkIV5CjdgjtYlxLyuiTxW7ZDq05GzIyYGTEzYmbEzBeAmfPVuPgxn0iS",
	"2h3hWcE0zRneYeMQ0wHckAwPpsIIgRRzhRIuJZ1Q7jamfyckkJEyc8s9/v4MxkKOaJqiIdE8qi8GOfpx",
	"ADeIMMeRcs1nqT1VJpdCi0SwM0gYNY3Zi8AUEInw6eamGBmaR9Zmtj8z6rDY3pvRWKuXEbjqSTcj89gl",
	"s3zrGPUM4unlgSq7lOopVX6eRJiMMBlhMsLki4fJ+/v/CwAA//9M7LkTK+UAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
