//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AgentState.
const (
	AgentStateIdle     AgentState = "idle"
	AgentStateRunning  AgentState = "running"
	AgentStateStopping AgentState = "stopping"
)

// Defines values for AgentOutputResponseType.
const (
	AgentOutputResponseTypeAgent      AgentOutputResponseType = "agent"
	AgentOutputResponseTypeStatus     AgentOutputResponseType = "status"
	AgentOutputResponseTypeTool       AgentOutputResponseType = "tool"
	AgentOutputResponseTypeToolResult AgentOutputResponseType = "tool_result"
	AgentOutputResponseTypeUsage      AgentOutputResponseType = "usage"
)

// Defines values for AgentSummaryState.
const (
	AgentSummaryStateIdle     AgentSummaryState = "idle"
	AgentSummaryStateRunning  AgentSummaryState = "running"
	AgentSummaryStateStopping AgentSummaryState = "stopping"
)

// Defines values for AgentUpdateState.
const (
	AgentUpdateStateIdle     AgentUpdateState = "idle"
	AgentUpdateStateRunning  AgentUpdateState = "running"
	AgentUpdateStateStopping AgentUpdateState = "stopping"
)

// Defines values for ErrorCode.
const (
	Conflict             ErrorCode = "conflict"
	CursorInvalid        ErrorCode = "cursor_invalid"
	Forbidden            ErrorCode = "forbidden"
	IdempotencyConflict  ErrorCode = "idempotency_conflict"
	Internal             ErrorCode = "internal"
	Invalid              ErrorCode = "invalid"
	InvalidLimit         ErrorCode = "invalid_limit"
	InvalidMessage       ErrorCode = "invalid_message"
	InvalidProject       ErrorCode = "invalid_project"
	InvalidSettings      ErrorCode = "invalid_settings"
	InvalidWorkspace     ErrorCode = "invalid_workspace"
	MethodNotAllowed     ErrorCode = "method_not_allowed"
	NotFound             ErrorCode = "not_found"
	NotPending           ErrorCode = "not_pending"
	NotRunning           ErrorCode = "not_running"
	ProjectExists        ErrorCode = "project_exists"
	ProjectNotEmpty      ErrorCode = "project_not_empty"
	Settled              ErrorCode = "settled"
	ShuttingDown         ErrorCode = "shutting_down"
	StorageFailed        ErrorCode = "storage_failed"
	TooLarge             ErrorCode = "too_large"
	TurnRequired         ErrorCode = "turn_required"
	UnsupportedMediaType ErrorCode = "unsupported_media_type"
	WorkspaceFailed      ErrorCode = "workspace_failed"
	WorkspaceLocked      ErrorCode = "workspace_locked"
	WorkspaceUnavailable ErrorCode = "workspace_unavailable"
)

// Defines values for EventType.
const (
	AgentCreated     EventType = "agent.created"
	AgentUpdated     EventType = "agent.updated"
	Conversation     EventType = "conversation"
	MessageCancelled EventType = "message.cancelled"
	MessageQueued    EventType = "message.queued"
	Output           EventType = "output"
	TurnCancelled    EventType = "turn.cancelled"
	TurnCompleted    EventType = "turn.completed"
	TurnFailed       EventType = "turn.failed"
	TurnInterrupted  EventType = "turn.interrupted"
	TurnStarted      EventType = "turn.started"
)

// Defines values for HealthApiVersion.
const (
	N1 HealthApiVersion = "1"
)

// Defines values for QueuedMessageStatus.
const (
	QueuedMessageStatusCancelled   QueuedMessageStatus = "cancelled"
	QueuedMessageStatusCompleted   QueuedMessageStatus = "completed"
	QueuedMessageStatusFailed      QueuedMessageStatus = "failed"
	QueuedMessageStatusInterrupted QueuedMessageStatus = "interrupted"
	QueuedMessageStatusPending     QueuedMessageStatus = "pending"
	QueuedMessageStatusRunning     QueuedMessageStatus = "running"
)

// Defines values for WSAckType.
const (
	Ack WSAckType = "ack"
)

// Defines values for WSErrorType.
const (
	WSErrorTypeError WSErrorType = "error"
)

// Defines values for WSEventType.
const (
	WSEventTypeEvent WSEventType = "event"
)

// Defines values for WSEventReferenceType.
const (
	EventRef WSEventReferenceType = "event_ref"
)

// Defines values for WSInventoryType.
const (
	Inventory WSInventoryType = "inventory"
)

// Defines values for WSSubmitType.
const (
	Submit WSSubmitType = "submit"
)

// Defines values for WSSubscribeType.
const (
	Subscribe WSSubscribeType = "subscribe"
)

// Defines values for WSSubscribedType.
const (
	Subscribed WSSubscribedType = "subscribed"
)

// Defines values for WorkspaceMode.
const (
	WorkspaceModeCurrentCheckout WorkspaceMode = "current_checkout"
	WorkspaceModeWorktree        WorkspaceMode = "worktree"
)

// Defines values for WorkspaceStatus.
const (
	Creating WorkspaceStatus = "creating"
	Draft    WorkspaceStatus = "draft"
	Failed   WorkspaceStatus = "failed"
	Fetching WorkspaceStatus = "fetching"
	Ready    WorkspaceStatus = "ready"
)

// Defines values for WorkspaceSelectionMode.
const (
	WorkspaceSelectionModeCurrentCheckout WorkspaceSelectionMode = "current_checkout"
	WorkspaceSelectionModeWorktree        WorkspaceSelectionMode = "worktree"
)

// Agent defines model for Agent.
type Agent struct {
	ActiveSettings     *Settings        `json:"active_settings,omitempty"`
	ContextUsage       *ContextUsage    `json:"context_usage,omitempty"`
	CreatedAt          time.Time        `json:"created_at"`
	Cursor             int64            `json:"cursor"`
	Held               bool             `json:"held"`
	Id                 string           `json:"id"`
	LastResponseCursor *int64           `json:"last_response_cursor,omitempty"`
	Messages           *[]Message       `json:"messages,omitempty"`
	ParentAgentId      *string          `json:"parent_agent_id,omitempty"`
	ProjectId          string           `json:"project_id"`
	Queue              *[]QueuedMessage `json:"queue,omitempty"`
	ReadCursor         *int64           `json:"read_cursor,omitempty"`
	Settings           Settings         `json:"settings"`
	Settled            bool             `json:"settled"`
	State              AgentState       `json:"state"`
	Title              string           `json:"title"`
	UpdatedAt          time.Time        `json:"updated_at"`
	Workspace          *Workspace       `json:"workspace,omitempty"`
}

// AgentState defines model for Agent.State.
type AgentState string

// AgentOutput Retained agent.AgentResponse. PascalCase field names are intentional compatibility with the existing runtime output payload.
type AgentOutput struct {
	// Content Display/provider-context output, possibly capped for tool results.
	Content string `json:"Content"`

	// FullToolOutput Complete uncapped tool stdout/stderr including cancellation/failure annotations; empty on non-tool-result output.
	FullToolOutput string                  `json:"FullToolOutput"`
	ResponseType   AgentOutputResponseType `json:"ResponseType"`
	ToolCallID     string                  `json:"ToolCallID"`
	ToolName       string                  `json:"ToolName"`
}

// AgentOutputResponseType defines model for AgentOutput.ResponseType.
type AgentOutputResponseType string

// AgentSummary defines model for AgentSummary.
type AgentSummary struct {
	ActiveSettings     *Settings         `json:"active_settings,omitempty"`
	ContextUsage       *ContextUsage     `json:"context_usage,omitempty"`
	CreatedAt          time.Time         `json:"created_at"`
	Cursor             int64             `json:"cursor"`
	Held               bool              `json:"held"`
	Id                 string            `json:"id"`
	LastResponseCursor *int64            `json:"last_response_cursor,omitempty"`
	ParentAgentId      *string           `json:"parent_agent_id,omitempty"`
	ProjectId          string            `json:"project_id"`
	ReadCursor         *int64            `json:"read_cursor,omitempty"`
	Settings           Settings          `json:"settings"`
	Settled            bool              `json:"settled"`
	State              AgentSummaryState `json:"state"`
	Title              string            `json:"title"`
	UpdatedAt          time.Time         `json:"updated_at"`
	Workspace          *Workspace        `json:"workspace,omitempty"`
}

// AgentSummaryState defines model for AgentSummary.State.
type AgentSummaryState string

// AgentUpdate State payload for agent.created and agent.updated. The enclosing Event supplies agent_id, cursor and created_at. This is not a complete Agent resource; it deliberately excludes history and queue.
type AgentUpdate struct {
	ActiveSettings     *NullableSettings `json:"active_settings"`
	ContextUsage       ContextUsage      `json:"context_usage"`
	Held               bool              `json:"held"`
	Id                 string            `json:"id"`
	LastResponseCursor *int64            `json:"last_response_cursor,omitempty"`
	ParentAgentId      *string           `json:"parent_agent_id,omitempty"`
	ProjectId          string            `json:"project_id"`
	ReadCursor         *int64            `json:"read_cursor,omitempty"`
	Settings           Settings          `json:"settings"`
	Settled            bool              `json:"settled"`
	State              AgentUpdateState  `json:"state"`
	Title              string            `json:"title"`
	Workspace          *Workspace        `json:"workspace,omitempty"`
}

// AgentUpdateState defines model for AgentUpdate.State.
type AgentUpdateState string

// ContentPart defines model for ContentPart.
type ContentPart struct {
	ImageUrl             *ContentPart_ImageUrl  `json:"image_url,omitempty"`
	Text                 *string                `json:"text,omitempty"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContentPartImageUrl1 defines model for .
type ContentPartImageUrl1 = string

// ContentPart_ImageUrl defines model for ContentPart.ImageUrl.
type ContentPart_ImageUrl struct {
	union json.RawMessage
}

// ContextUsage defines model for ContextUsage.
type ContextUsage struct {
	ContextWindow   int64  `json:"context_window"`
	Estimated       bool   `json:"estimated"`
	EstimatedTokens int64  `json:"estimated_tokens"`
	InputTokens     int64  `json:"input_tokens"`
	Known           bool   `json:"known"`
	Model           string `json:"model"`
	OutputTokens    int64  `json:"output_tokens"`
}

// ConversationDelta New committed messages appended since the previous conversation event, not a full conversation snapshot.
type ConversationDelta = []Message

// CreateAgentRequest Creates an idle agent unless prompt is supplied. Optional parent_agent_id must identify an existing agent on this server and is immutable after creation. Omitted directory and workspace overrides share an established parent worktree in the same project; otherwise project defaults apply.
type CreateAgentRequest struct {
	ParentAgentId *string        `json:"parent_agent_id,omitempty"`
	ProjectId     string         `json:"project_id"`
	Prompt        *string        `json:"prompt,omitempty"`
	Settings      *SettingsPatch `json:"settings,omitempty"`
	Title         *string        `json:"title,omitempty"`

	// WorkingDirectory Absolute server-local project root or established managed worktree path. Overrides implicit parent workspace inheritance; worktree mode still creates a fresh worktree.
	WorkingDirectory *string             `json:"working_directory,omitempty"`
	Workspace        *WorkspaceSelection `json:"workspace,omitempty"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Defaults          Settings            `json:"defaults"`
	Name              string              `json:"name"`
	Root              string              `json:"root"`
	WorkspaceDefaults *WorkspaceSelection `json:"workspace_defaults,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    ErrorCode `json:"code"`
		Message string    `json:"message"`
	} `json:"error"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Event defines model for Event.
type Event struct {
	AgentId   string    `json:"agent_id"`
	CreatedAt time.Time `json:"created_at"`
	Cursor    int64     `json:"cursor"`

	// Data Payload selected by Event.type; see x-event-data-schemas on Event and websocket.md.
	Data EventData `json:"data"`
	Type EventType `json:"type"`
}

// EventType defines model for Event.Type.
type EventType string

// EventData Payload selected by Event.type; see x-event-data-schemas on Event and websocket.md.
type EventData struct {
	union json.RawMessage
}

// EventPage defines model for EventPage.
type EventPage struct {
	Events     []Event `json:"events"`
	NextCursor int64   `json:"next_cursor"`
}

// FunctionCall defines model for FunctionCall.
type FunctionCall struct {
	// Arguments JSON-encoded function arguments.
	Arguments string `json:"arguments"`
	Name      string `json:"name"`
}

// Health defines model for Health.
type Health struct {
	ApiVersion HealthApiVersion `json:"api_version"`
}

// HealthApiVersion defines model for Health.ApiVersion.
type HealthApiVersion string

// HistoryPage defines model for HistoryPage.
type HistoryPage struct {
	Messages   []Message `json:"messages"`
	NextCursor int64     `json:"next_cursor"`
}

// ImageURL defines model for ImageURL.
type ImageURL struct {
	Detail               *string                `json:"detail,omitempty"`
	Url                  string                 `json:"url"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Message Provider-neutral retained conversation message, including reasoning provenance and tool results. Unknown provider fields are preserved.
type Message struct {
	// Content Original provider body: plain text, typed multimodal parts, or null. Replayed without normalization.
	Content          *MessageContent    `json:"content"`
	Reasoning        *string            `json:"reasoning,omitempty"`
	ReasoningDetails *[]ReasoningDetail `json:"reasoning_details,omitempty"`
	Role             string             `json:"role"`

	// SourceModel Origin model for opaque reasoning replay; not forwarded as a provider message field.
	SourceModel          *string                `json:"source_model,omitempty"`
	ToolCallId           *string                `json:"tool_call_id,omitempty"`
	ToolCalls            *[]ToolCall            `json:"tool_calls,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MessageContent Original provider body: plain text, typed multimodal parts, or null. Replayed without normalization.
type MessageContent struct {
	union json.RawMessage
}

// MessageContent0 defines model for .
type MessageContent0 = string

// MessageContent1 defines model for .
type MessageContent1 = []ContentPart

// Model defines model for Model.
type Model struct {
	ContextWindow int64    `json:"context_window"`
	DefaultEffort string   `json:"default_effort"`
	Efforts       []string `json:"efforts"`
	Id            string   `json:"id"`
	Name          string   `json:"name"`
	Provider      string   `json:"provider"`
}

// NullableSettings defines model for NullableSettings.
type NullableSettings struct {
	Effort string `json:"effort"`
	Model  string `json:"model"`
}

// PatchAgentRequest defines model for PatchAgentRequest.
type PatchAgentRequest struct {
	ReadCursor *int64 `json:"read_cursor,omitempty"`
	Settled    *bool  `json:"settled,omitempty"`
}

// PatchProjectRequest defines model for PatchProjectRequest.
type PatchProjectRequest struct {
	Defaults          *Settings           `json:"defaults,omitempty"`
	Name              *string             `json:"name,omitempty"`
	WorkspaceDefaults *WorkspaceSelection `json:"workspace_defaults,omitempty"`
}

// Project defines model for Project.
type Project struct {
	Defaults Settings `json:"defaults"`

	// GitBranch Live server-side Git branch (or detached commit), populated on GET project; omitted outside Git repositories.
	GitBranch         *string             `json:"git_branch,omitempty"`
	Id                string              `json:"id"`
	Name              string              `json:"name"`
	Root              string              `json:"root"`
	WorkspaceDefaults *WorkspaceSelection `json:"workspace_defaults,omitempty"`
}

// ProjectBranches defines model for ProjectBranches.
type ProjectBranches struct {
	Branches      []string `json:"branches"`
	DefaultBranch string   `json:"default_branch"`
	IsGit         bool     `json:"is_git"`
}

// QueuedMessage defines model for QueuedMessage.
type QueuedMessage struct {
	CreatedAt time.Time           `json:"created_at"`
	Error     *string             `json:"error,omitempty"`
	Id        string              `json:"id"`
	Status    QueuedMessageStatus `json:"status"`
	Text      string              `json:"text"`
}

// QueuedMessageStatus defines model for QueuedMessage.Status.
type QueuedMessageStatus string

// ReasoningDetail Opaque extended thinking record. Unknown provider fields, encrypted data and signatures must be preserved unchanged.
type ReasoningDetail struct {
	Data                 *json.RawMessage       `json:"data"`
	Format               *string                `json:"format,omitempty"`
	Id                   *string                `json:"id,omitempty"`
	Index                *int64                 `json:"index,omitempty"`
	Signature            *string                `json:"signature,omitempty"`
	Summary              *json.RawMessage       `json:"summary"`
	Text                 *string                `json:"text,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Settings defines model for Settings.
type Settings struct {
	Effort string `json:"effort"`
	Model  string `json:"model"`
}

// SettingsPatch defines model for SettingsPatch.
type SettingsPatch struct {
	Effort *string `json:"effort,omitempty"`
	Model  *string `json:"model,omitempty"`
}

// StopRequest defines model for StopRequest.
type StopRequest struct {
	TurnId string `json:"turn_id"`
}

// SubmitMessageRequest defines model for SubmitMessageRequest.
type SubmitMessageRequest struct {
	Text string `json:"text"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	Function FunctionCall `json:"function"`
	Id       string       `json:"id"`
	Index    int64        `json:"index"`
	Type     string       `json:"type"`
}

// WSAck defines model for WSAck.
type WSAck struct {
	AgentId   string    `json:"agent_id"`
	MessageId string    `json:"message_id"`
	RequestId string    `json:"request_id"`
	Status    string    `json:"status"`
	Type      WSAckType `json:"type"`
}

// WSAckType defines model for WSAck.Type.
type WSAckType string

// WSError defines model for WSError.
type WSError struct {
	Code      ErrorCode   `json:"code"`
	Message   string      `json:"message"`
	RequestId *string     `json:"request_id,omitempty"`
	Type      WSErrorType `json:"type"`
}

// WSErrorType defines model for WSError.Type.
type WSErrorType string

// WSEvent defines model for WSEvent.
type WSEvent struct {
	Event Event       `json:"event"`
	Type  WSEventType `json:"type"`
}

// WSEventType defines model for WSEvent.Type.
type WSEventType string

// WSEventReference defines model for WSEventReference.
type WSEventReference struct {
	AgentId string               `json:"agent_id"`
	Cursor  int64                `json:"cursor"`
	Type    WSEventReferenceType `json:"type"`
	Url     string               `json:"url"`
}

// WSEventReferenceType defines model for WSEventReference.Type.
type WSEventReferenceType string

// WSInventory defines model for WSInventory.
type WSInventory struct {
	Agent AgentSummary    `json:"agent"`
	Type  WSInventoryType `json:"type"`
}

// WSInventoryType defines model for WSInventory.Type.
type WSInventoryType string

// WSSubmit defines model for WSSubmit.
type WSSubmit struct {
	AgentId        string       `json:"agent_id"`
	IdempotencyKey string       `json:"idempotency_key"`
	RequestId      string       `json:"request_id"`
	Text           string       `json:"text"`
	Type           WSSubmitType `json:"type"`
}

// WSSubmitType defines model for WSSubmit.Type.
type WSSubmitType string

// WSSubscribe defines model for WSSubscribe.
type WSSubscribe struct {
	AgentIds     *[]string         `json:"agent_ids,omitempty"`
	Cursors      *map[string]int64 `json:"cursors,omitempty"`
	RequestId    string            `json:"request_id"`
	SubscribeAll *bool             `json:"subscribe_all,omitempty"`
	Type         WSSubscribeType   `json:"type"`
}

// WSSubscribeType defines model for WSSubscribe.Type.
type WSSubscribeType string

// WSSubscribed defines model for WSSubscribed.
type WSSubscribed struct {
	RequestId string           `json:"request_id"`
	Type      WSSubscribedType `json:"type"`
}

// WSSubscribedType defines model for WSSubscribed.Type.
type WSSubscribedType string

// Workspace defines model for Workspace.
type Workspace struct {
	BaseBranch *string       `json:"base_branch,omitempty"`
	BaseCommit *string       `json:"base_commit,omitempty"`
	Branch     *string       `json:"branch,omitempty"`
	Error      *string       `json:"error,omitempty"`
	Locked     bool          `json:"locked"`
	Mode       WorkspaceMode `json:"mode"`
	Path       *string       `json:"path,omitempty"`

	// Shared Reuses an existing managed worktree rather than provisioning a new one.
	Shared *bool           `json:"shared,omitempty"`
	Status WorkspaceStatus `json:"status"`
}

// WorkspaceMode defines model for Workspace.Mode.
type WorkspaceMode string

// WorkspaceStatus defines model for Workspace.Status.
type WorkspaceStatus string

// WorkspaceSelection defines model for WorkspaceSelection.
type WorkspaceSelection struct {
	BaseBranch *string                `json:"base_branch,omitempty"`
	Mode       WorkspaceSelectionMode `json:"mode"`
}

// WorkspaceSelectionMode defines model for WorkspaceSelection.Mode.
type WorkspaceSelectionMode string

// ListAgentsParams defines parameters for ListAgents.
type ListAgentsParams struct {
	IncludeSettled *bool   `form:"include_settled,omitempty" json:"include_settled,omitempty"`
	ProjectId      *string `form:"project_id,omitempty" json:"project_id,omitempty"`
	Page           *int64  `form:"page,omitempty" json:"page,omitempty"`
	PageSize       *int64  `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// CreateAgentParams defines parameters for CreateAgent.
type CreateAgentParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	After *int64 `form:"after,omitempty" json:"after,omitempty"`
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetHistoryParams defines parameters for GetHistory.
type GetHistoryParams struct {
	After *int64 `form:"after,omitempty" json:"after,omitempty"`
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// SubmitMessageParams defines parameters for SubmitMessage.
type SubmitMessageParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = CreateAgentRequest

// PatchAgentJSONRequestBody defines body for PatchAgent for application/json ContentType.
type PatchAgentJSONRequestBody = PatchAgentRequest

// SubmitMessageJSONRequestBody defines body for SubmitMessage for application/json ContentType.
type SubmitMessageJSONRequestBody = SubmitMessageRequest

// PatchAgentSettingsJSONRequestBody defines body for PatchAgentSettings for application/json ContentType.
type PatchAgentSettingsJSONRequestBody = SettingsPatch

// StopAgentJSONRequestBody defines body for StopAgent for application/json ContentType.
type StopAgentJSONRequestBody = StopRequest

// PatchAgentWorkspaceJSONRequestBody defines body for PatchAgentWorkspace for application/json ContentType.
type PatchAgentWorkspaceJSONRequestBody = WorkspaceSelection

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// PatchProjectJSONRequestBody defines body for PatchProject for application/json ContentType.
type PatchProjectJSONRequestBody = PatchProjectRequest

// Getter for additional properties for ContentPart. Returns the specified
// element and whether it was found
func (a ContentPart) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContentPart
func (a *ContentPart) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContentPart to handle AdditionalProperties
func (a *ContentPart) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["image_url"]; found {
		err = json.Unmarshal(raw, &a.ImageUrl)
		if err != nil {
			return fmt.Errorf("error reading 'image_url': %w", err)
		}
		delete(object, "image_url")
	}

	if raw, found := object["text"]; found {
		err = json.Unmarshal(raw, &a.Text)
		if err != nil {
			return fmt.Errorf("error reading 'text': %w", err)
		}
		delete(object, "text")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContentPart to handle AdditionalProperties
func (a ContentPart) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ImageUrl != nil {
		object["image_url"], err = json.Marshal(a.ImageUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'image_url': %w", err)
		}
	}

	if a.Text != nil {
		object["text"], err = json.Marshal(a.Text)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'text': %w", err)
		}
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ImageURL. Returns the specified
// element and whether it was found
func (a ImageURL) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ImageURL
func (a *ImageURL) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ImageURL to handle AdditionalProperties
func (a *ImageURL) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &a.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
		delete(object, "url")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ImageURL to handle AdditionalProperties
func (a ImageURL) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["url"], err = json.Marshal(a.Url)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'url': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Message. Returns the specified
// element and whether it was found
func (a Message) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Message
func (a *Message) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Message to handle AdditionalProperties
func (a *Message) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return fmt.Errorf("error reading 'content': %w", err)
		}
		delete(object, "content")
	}

	if raw, found := object["reasoning"]; found {
		err = json.Unmarshal(raw, &a.Reasoning)
		if err != nil {
			return fmt.Errorf("error reading 'reasoning': %w", err)
		}
		delete(object, "reasoning")
	}

	if raw, found := object["reasoning_details"]; found {
		err = json.Unmarshal(raw, &a.ReasoningDetails)
		if err != nil {
			return fmt.Errorf("error reading 'reasoning_details': %w", err)
		}
		delete(object, "reasoning_details")
	}

	if raw, found := object["role"]; found {
		err = json.Unmarshal(raw, &a.Role)
		if err != nil {
			return fmt.Errorf("error reading 'role': %w", err)
		}
		delete(object, "role")
	}

	if raw, found := object["source_model"]; found {
		err = json.Unmarshal(raw, &a.SourceModel)
		if err != nil {
			return fmt.Errorf("error reading 'source_model': %w", err)
		}
		delete(object, "source_model")
	}

	if raw, found := object["tool_call_id"]; found {
		err = json.Unmarshal(raw, &a.ToolCallId)
		if err != nil {
			return fmt.Errorf("error reading 'tool_call_id': %w", err)
		}
		delete(object, "tool_call_id")
	}

	if raw, found := object["tool_calls"]; found {
		err = json.Unmarshal(raw, &a.ToolCalls)
		if err != nil {
			return fmt.Errorf("error reading 'tool_calls': %w", err)
		}
		delete(object, "tool_calls")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Message to handle AdditionalProperties
func (a Message) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["content"], err = json.Marshal(a.Content)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'content': %w", err)
	}

	if a.Reasoning != nil {
		object["reasoning"], err = json.Marshal(a.Reasoning)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reasoning': %w", err)
		}
	}

	if a.ReasoningDetails != nil {
		object["reasoning_details"], err = json.Marshal(a.ReasoningDetails)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reasoning_details': %w", err)
		}
	}

	object["role"], err = json.Marshal(a.Role)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'role': %w", err)
	}

	if a.SourceModel != nil {
		object["source_model"], err = json.Marshal(a.SourceModel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'source_model': %w", err)
		}
	}

	if a.ToolCallId != nil {
		object["tool_call_id"], err = json.Marshal(a.ToolCallId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tool_call_id': %w", err)
		}
	}

	if a.ToolCalls != nil {
		object["tool_calls"], err = json.Marshal(a.ToolCalls)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tool_calls': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ReasoningDetail. Returns the specified
// element and whether it was found
func (a ReasoningDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ReasoningDetail
func (a *ReasoningDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ReasoningDetail to handle AdditionalProperties
func (a *ReasoningDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["data"]; found {
		err = json.Unmarshal(raw, &a.Data)
		if err != nil {
			return fmt.Errorf("error reading 'data': %w", err)
		}
		delete(object, "data")
	}

	if raw, found := object["format"]; found {
		err = json.Unmarshal(raw, &a.Format)
		if err != nil {
			return fmt.Errorf("error reading 'format': %w", err)
		}
		delete(object, "format")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["index"]; found {
		err = json.Unmarshal(raw, &a.Index)
		if err != nil {
			return fmt.Errorf("error reading 'index': %w", err)
		}
		delete(object, "index")
	}

	if raw, found := object["signature"]; found {
		err = json.Unmarshal(raw, &a.Signature)
		if err != nil {
			return fmt.Errorf("error reading 'signature': %w", err)
		}
		delete(object, "signature")
	}

	if raw, found := object["summary"]; found {
		err = json.Unmarshal(raw, &a.Summary)
		if err != nil {
			return fmt.Errorf("error reading 'summary': %w", err)
		}
		delete(object, "summary")
	}

	if raw, found := object["text"]; found {
		err = json.Unmarshal(raw, &a.Text)
		if err != nil {
			return fmt.Errorf("error reading 'text': %w", err)
		}
		delete(object, "text")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ReasoningDetail to handle AdditionalProperties
func (a ReasoningDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Data != nil {
		object["data"], err = json.Marshal(a.Data)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'data': %w", err)
		}
	}

	if a.Format != nil {
		object["format"], err = json.Marshal(a.Format)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'format': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Index != nil {
		object["index"], err = json.Marshal(a.Index)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'index': %w", err)
		}
	}

	if a.Signature != nil {
		object["signature"], err = json.Marshal(a.Signature)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'signature': %w", err)
		}
	}

	if a.Summary != nil {
		object["summary"], err = json.Marshal(a.Summary)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'summary': %w", err)
		}
	}

	if a.Text != nil {
		object["text"], err = json.Marshal(a.Text)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'text': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsImageURL returns the union data inside the ContentPart_ImageUrl as a ImageURL
func (t ContentPart_ImageUrl) AsImageURL() (ImageURL, error) {
	var body ImageURL
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURL overwrites any union data inside the ContentPart_ImageUrl as the provided ImageURL
func (t *ContentPart_ImageUrl) FromImageURL(v ImageURL) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURL performs a merge with any union data inside the ContentPart_ImageUrl, using the provided ImageURL
func (t *ContentPart_ImageUrl) MergeImageURL(v ImageURL) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsContentPartImageUrl1 returns the union data inside the ContentPart_ImageUrl as a ContentPartImageUrl1
func (t ContentPart_ImageUrl) AsContentPartImageUrl1() (ContentPartImageUrl1, error) {
	var body ContentPartImageUrl1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromContentPartImageUrl1 overwrites any union data inside the ContentPart_ImageUrl as the provided ContentPartImageUrl1
func (t *ContentPart_ImageUrl) FromContentPartImageUrl1(v ContentPartImageUrl1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeContentPartImageUrl1 performs a merge with any union data inside the ContentPart_ImageUrl, using the provided ContentPartImageUrl1
func (t *ContentPart_ImageUrl) MergeContentPartImageUrl1(v ContentPartImageUrl1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart_ImageUrl) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart_ImageUrl) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAgentUpdate returns the union data inside the EventData as a AgentUpdate
func (t EventData) AsAgentUpdate() (AgentUpdate, error) {
	var body AgentUpdate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentUpdate overwrites any union data inside the EventData as the provided AgentUpdate
func (t *EventData) FromAgentUpdate(v AgentUpdate) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentUpdate performs a merge with any union data inside the EventData, using the provided AgentUpdate
func (t *EventData) MergeAgentUpdate(v AgentUpdate) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQueuedMessage returns the union data inside the EventData as a QueuedMessage
func (t EventData) AsQueuedMessage() (QueuedMessage, error) {
	var body QueuedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueuedMessage overwrites any union data inside the EventData as the provided QueuedMessage
func (t *EventData) FromQueuedMessage(v QueuedMessage) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueuedMessage performs a merge with any union data inside the EventData, using the provided QueuedMessage
func (t *EventData) MergeQueuedMessage(v QueuedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentOutput returns the union data inside the EventData as a AgentOutput
func (t EventData) AsAgentOutput() (AgentOutput, error) {
	var body AgentOutput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentOutput overwrites any union data inside the EventData as the provided AgentOutput
func (t *EventData) FromAgentOutput(v AgentOutput) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentOutput performs a merge with any union data inside the EventData, using the provided AgentOutput
func (t *EventData) MergeAgentOutput(v AgentOutput) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConversationDelta returns the union data inside the EventData as a ConversationDelta
func (t EventData) AsConversationDelta() (ConversationDelta, error) {
	var body ConversationDelta
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConversationDelta overwrites any union data inside the EventData as the provided ConversationDelta
func (t *EventData) FromConversationDelta(v ConversationDelta) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConversationDelta performs a merge with any union data inside the EventData, using the provided ConversationDelta
func (t *EventData) MergeConversationDelta(v ConversationDelta) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventData) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventData) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMessageContent0 returns the union data inside the MessageContent as a MessageContent0
func (t MessageContent) AsMessageContent0() (MessageContent0, error) {
	var body MessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageContent0 overwrites any union data inside the MessageContent as the provided MessageContent0
func (t *MessageContent) FromMessageContent0(v MessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageContent0 performs a merge with any union data inside the MessageContent, using the provided MessageContent0
func (t *MessageContent) MergeMessageContent0(v MessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageContent1 returns the union data inside the MessageContent as a MessageContent1
func (t MessageContent) AsMessageContent1() (MessageContent1, error) {
	var body MessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageContent1 overwrites any union data inside the MessageContent as the provided MessageContent1
func (t *MessageContent) FromMessageContent1(v MessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageContent1 performs a merge with any union data inside the MessageContent, using the provided MessageContent1
func (t *MessageContent) MergeMessageContent1(v MessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MessageContent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MessageContent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /v1/agents)
	ListAgents(w http.ResponseWriter, r *http.Request, params ListAgentsParams)

	// (POST /v1/agents)
	CreateAgent(w http.ResponseWriter, r *http.Request, params CreateAgentParams)

	// (GET /v1/agents/{agent_id})
	GetAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (PATCH /v1/agents/{agent_id})
	PatchAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (POST /v1/agents/{agent_id}/continue)
	ContinueAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (GET /v1/agents/{agent_id}/events)
	GetEvents(w http.ResponseWriter, r *http.Request, agentId string, params GetEventsParams)

	// (GET /v1/agents/{agent_id}/events/{cursor})
	GetEvent(w http.ResponseWriter, r *http.Request, agentId string, cursor int64)

	// (GET /v1/agents/{agent_id}/history)
	GetHistory(w http.ResponseWriter, r *http.Request, agentId string, params GetHistoryParams)

	// (GET /v1/agents/{agent_id}/messages)
	ListMessages(w http.ResponseWriter, r *http.Request, agentId string)

	// (POST /v1/agents/{agent_id}/messages)
	SubmitMessage(w http.ResponseWriter, r *http.Request, agentId string, params SubmitMessageParams)

	// (DELETE /v1/agents/{agent_id}/messages/{message_id})
	DeletePending(w http.ResponseWriter, r *http.Request, agentId string, messageId string)

	// (PATCH /v1/agents/{agent_id}/settings)
	PatchAgentSettings(w http.ResponseWriter, r *http.Request, agentId string)

	// (POST /v1/agents/{agent_id}/stop)
	StopAgent(w http.ResponseWriter, r *http.Request, agentId string)

	// (PATCH /v1/agents/{agent_id}/workspace)
	PatchAgentWorkspace(w http.ResponseWriter, r *http.Request, agentId string)

	// (GET /v1/models)
	ListModels(w http.ResponseWriter, r *http.Request)

	// (GET /v1/projects)
	ListProjects(w http.ResponseWriter, r *http.Request)

	// (POST /v1/projects)
	CreateProject(w http.ResponseWriter, r *http.Request)

	// (DELETE /v1/projects/{project_id})
	DeleteProject(w http.ResponseWriter, r *http.Request, projectId string)

	// (GET /v1/projects/{project_id})
	GetProject(w http.ResponseWriter, r *http.Request, projectId string)

	// (PATCH /v1/projects/{project_id})
	PatchProject(w http.ResponseWriter, r *http.Request, projectId string)

	// (GET /v1/projects/{project_id}/branches)
	ListProjectBranches(w http.ResponseWriter, r *http.Request, projectId string)

	// (GET /v1/ws)
	WebSocket(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentsParams

	// ------------- Optional query parameter "include_settled" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_settled", r.URL.Query(), &params.IncludeSettled)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_settled", Err: err})
		return
	}

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAgent operation middleware
func (siw *ServerInterfaceWrapper) CreateAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateAgentParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgent operation middleware
func (siw *ServerInterfaceWrapper) GetAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAgent operation middleware
func (siw *ServerInterfaceWrapper) PatchAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ContinueAgent operation middleware
func (siw *ServerInterfaceWrapper) ContinueAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ContinueAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// ------------- Path parameter "cursor" -------------
	var cursor int64

	err = runtime.BindStyledParameterWithOptions("simple", "cursor", r.PathValue("cursor"), &cursor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, agentId, cursor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHistory operation middleware
func (siw *ServerInterfaceWrapper) GetHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHistoryParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHistory(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitMessage operation middleware
func (siw *ServerInterfaceWrapper) SubmitMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SubmitMessageParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitMessage(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePending operation middleware
func (siw *ServerInterfaceWrapper) DeletePending(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// ------------- Path parameter "message_id" -------------
	var messageId string

	err = runtime.BindStyledParameterWithOptions("simple", "message_id", r.PathValue("message_id"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "message_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePending(w, r, agentId, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAgentSettings operation middleware
func (siw *ServerInterfaceWrapper) PatchAgentSettings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAgentSettings(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopAgent operation middleware
func (siw *ServerInterfaceWrapper) StopAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopAgent(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAgentWorkspace operation middleware
func (siw *ServerInterfaceWrapper) PatchAgentWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agent_id" -------------
	var agentId string

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", r.PathValue("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAgentWorkspace(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchProject operation middleware
func (siw *ServerInterfaceWrapper) PatchProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectBranches operation middleware
func (siw *ServerInterfaceWrapper) ListProjectBranches(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "project_id" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "project_id", r.PathValue("project_id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectBranches(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WebSocket operation middleware
func (siw *ServerInterfaceWrapper) WebSocket(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WebSocket(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents", wrapper.ListAgents)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents", wrapper.CreateAgent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}", wrapper.GetAgent)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/agents/{agent_id}", wrapper.PatchAgent)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents/{agent_id}/continue", wrapper.ContinueAgent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/events", wrapper.GetEvents)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/events/{cursor}", wrapper.GetEvent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/history", wrapper.GetHistory)
	m.HandleFunc("GET "+options.BaseURL+"/v1/agents/{agent_id}/messages", wrapper.ListMessages)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents/{agent_id}/messages", wrapper.SubmitMessage)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/agents/{agent_id}/messages/{message_id}", wrapper.DeletePending)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/agents/{agent_id}/settings", wrapper.PatchAgentSettings)
	m.HandleFunc("POST "+options.BaseURL+"/v1/agents/{agent_id}/stop", wrapper.StopAgent)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/agents/{agent_id}/workspace", wrapper.PatchAgentWorkspace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/models", wrapper.ListModels)
	m.HandleFunc("GET "+options.BaseURL+"/v1/projects", wrapper.ListProjects)
	m.HandleFunc("POST "+options.BaseURL+"/v1/projects", wrapper.CreateProject)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/projects/{project_id}", wrapper.DeleteProject)
	m.HandleFunc("GET "+options.BaseURL+"/v1/projects/{project_id}", wrapper.GetProject)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/projects/{project_id}", wrapper.PatchProject)
	m.HandleFunc("GET "+options.BaseURL+"/v1/projects/{project_id}/branches", wrapper.ListProjectBranches)
	m.HandleFunc("GET "+options.BaseURL+"/v1/ws", wrapper.WebSocket)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd3XMbN5L/V7p495BUUZTk2Hu30pMtO1nvxZbOcspXtZVigTNNEisMMAYwlBiX/vcr",
	"NDCfHFIkLcmKgydbHHx1o4FffwH4MkhUliuJ0prByZeBSeaYMfrvyxlK6/7D0pRbriQTF1rlqC1HMziZ",
	"MmFwOMgbP30ZsMTyBY4NWsvljH76T43TwcngPw7rjg5DL4eXZbnb4SBR0uKNHReGzfCuime+8G9U1lXW",
	"yCymY0YDniqduf8NUmbxwPIMB8OBXeY4OBkYq7mcUZ1CG6Vb5bm0f3s+GA4yLnlWZIOTo6oelxZnqF3F",
	"OYrUVQtfJkoJZNJ94fR7xm5+RTmz88HJsxd/o9bKv497xiGYsWONJlfS4HjvUWVoHDeI59xidifz3/kK",
	"rm5ojWnNlu7vnGmUdsycBIz3IirX6t+Y7Fn5c4EFbk3H/7rS6QZqNLJ0f77uI8uujsA1QmIss0QdStfp",
	"vwY8FU5AdSGlY4ArofLc/ff3HuZYbgU2Wq6/FHm68yK4VvrK5Cy5c8V9qgreEks/F1w7Ct3wB635LofY",
	"YF3NkZL8sIqqVdhawi1Sah6oievCjZq2pvPC5sXdG1SKJtE8d98HJ4MPaBmXmALJ9oga+hDW3ggumEmY",
	"OGMGYcpRpCBZhgaYRnASIX0n4NjDLJ9wwe0Srrmdg50j4A03jl7QhXT8BkUjhJwthWLpaNDdLWkX83ts",
	"e5SvuckFWx7mWi14ivogbI6hxSHkyhg+EUtIWJ5jClOlwSolQKMphDWjvrn+uRDio1KiZly71zOV5QIt",
	"QiFDs9Sksakq7KGxKWoNXCaiSB2VCZMJCsFc7cMp46LQCExKZekncwqY5XYJSoJU8sC1deCHF8joHWQ5",
	"GR/pQ71IaL5cBaVE+GfsWwsyVTgx8+DRt2wc4WdMiLeve9eO+/yeZX0LqyPu5aR1htrqodHeCtvXyvNl",
	"kWVMLyPi/lkQ9xujZIS17xLWfqMyO8Lapeu9BBpCA49voXdgskS8MIQRfHSIJROhjNvM3yxQWjBFngvu",
	"EC/I9BA8IdRATYqrzQ1wA1JZYASIhBxEgQMhVegET4FbSFHwCWpmUSwBbxx6oIE5N1bpJbVL6t4qOu64",
	"s70vhGATgfe2w8VN5y+86TzWBtIV8k1bSkuY+/aPoJpcML1BLba6WFEieMZmOC60cH8oiefTwcm/NtP9",
	"1lX57cOvg9vhCvt+d6zFG9vLWRsUu81aFn1dS2O5SndTlUoGXnOZqute8V0VWTSWZ27b6xfA6vPYqiuU",
	"ZstWucwLu1uVK6muZf8gMpWi6GW2V7R36agzD77pzoC77fawYdjldklAk6Nr5neB2pAJ8RqFZat2ynu8",
	"doiTceugrfR7gDNZZIopGC4TJIss17jgqjCQNFoFdFg3DNA1LYRofzaS5WauyDz5WkfKGUFmsDI/F2h2",
	"tVd9AwaYBLe1eWCGQgo0BnKtstw6GA7AnY7gPA9GagcoICuMBZ46I3bqcLc2V32bSoJ1oG5QL9ADvoP4",
	"LCusg1VgU4va6wBcyRGcB/6nXGNSYXm1b4JaoNbcYb2ZM7IMAY1rips5pmF4VN5qdPY1zZhhmZs22jRP",
	"Qdk56mtuqp8gxSlzBq6bbbFcVRq+MTz6GelUPD56/t8v/uvuyrui4wWzybwFY93R9sIal7NxNWmrq+vl",
	"xChRWAyCcCBU4qQp8F8rZUHp1lRmTLIZpvVc5szOR3BeCQDPcsETbpuT7oWEyzlqbpl0ymJV3206YCx3",
	"K7OUf5hqNPOqjJv5BrXPj/5+N393x/RLFJgQX7r7YkNKencxGvaFL7Ttym9Lcinpu+hKMngwdlXqlOrK",
	"7G4MHW872C04K73XhMY0rLnQx+U3Wns1dAe24h51EpXeKTM0ljNXsPbF363mUMt1+VUiO+X96Nfy4iwM",
	"tNKG5YIJUj3D/8ZBbhu/NFTP8qd6oTTnWKjkivTS+qcp46LzUyHZgnGyxBotlgTWvwiecfLnFVqOKxKH",
	"A6nseKoKGTTeqeA02nK9EWiZxg+uPPkZXdspZrmyKJPluFHXFXGqgTcI3F8N86DStr1RM65ZZuYFcWac",
	"er3FGaxOTa6IdjqTlkzQBNq5SmkwTAh1Td+tUmPBNJFdSAfRSjsVKcOUs7H1XsOp0hOepih7DRQyy3f1",
	"CO6PfQ/l1DvuU2hT5pW7javK0f/aFWxYDi2XcOnicLZU08FRr6oR+ReaPwTPtZ+kQsuRsUzb+s/SnVH9",
	"UE05/UXzrou8WaPRoteNvfhWWmXP7HaWdjVtDedRkBHiVGt2VnaA4eDmgPTaA1f4oBHGbXNpDZ+bnqcu",
	"I7eq0qJ1vYOlo9r3TclWUb6Vyd2yVpibTSSdl9PXmdgte+gI0C61gpTtUqUpirvUKwV+u5BquRG9Zn3m",
	"2EXwOhqCdExhsvTuxJET0VMwiNAnnM7i8G5HMhxwYhzA2FFGkbLtvBBNIbwd7hYn3qLlIAt3lV0VbHKB",
	"EHEXu/spiFXbx/E9RvQYn9KZ33v66rp6hx9Su80+NeTnQpJad8aE2BW39KzISsrbIvbPy/P3ByidtpTC",
	"NHQBVYXeQKLcKpoXtM267z6i/oFMOMjcjZycj51UEAU1aB1vgQSNmr3D8b7zPSTrPnNE7lG6qmHdLV+V",
	"23En/2aKlvF+D1lwem6eEVeobzTvaj1/02A6+2UZ1JdYWM0E6DInoeWGCkwZNiLuGplRTnF15vgCpcMm",
	"2jxboX/4TZKrDcrsAZ/L4NMYco1k1/dkIyR1NsIWIlGGwX1MwA+rl8HV17Gfhe2F70NZ87Wfvr7UHrXG",
	"f+8DUOPKM9qegnPNZ1ySn0FQtEzl7HOBDQZrzAVbnpKTcKr0NdNu62EGWM3WMEOevb17EGUpJEyIoI6v",
	"L7A9V8o0g1V2dISWeDOspnWD/K7NQ/F88u4fT/NEpcsTyAXjEize2CG4RlPICmF5plLveLRmCEqDLIQY",
	"wQdiJaaUKKMKC9JtFYL/4R2JbtGH0F25Xmrs7zJsSx41AyErbHLQ/K6Ui/sNH2yOfgVfxhinU6X7gyP+",
	"U1sY1kRQ6kWwRrbWACCRRZN5975H1kiAyKpWj2u/HPYKjX1CtxKovWsauuLR0ZYqbjaM3b8971mN1Waw",
	"k1W8JiCygUDyy+7k88/YTfPXYxpS55c21V8fh10TU71dR9COzsy7CHhE9+a9uSlXGRO8aQ/v2Z1xO55o",
	"JpP56i79K19U3nrDU4RfuAVfGH5QGhzuJnPSL7KM2x+HkKu8EJQYoiT88uZjI+ISojqqsFVTGnNluFWa",
	"Y7+qvZevae32VHqjH8fd3NzitvE5hyl/RexFs+PUTxrVtt/gy021FoDVKTDjGbdrFnSLXl9wWA9lpf0+",
	"stvG847AuYdXsXLT34+whQTRhh1WO4RrZ3DT79f28lbevtof1JtP0p/00CdyVLSRubrJuUdpsW1deCeL",
	"49xrt3hjfYDczrm88lpuonS61mIYAspEL3MK8zLLyNYwfCaZLTQaH1KeNIwKKGQyZ3LWZ16U7t4umt8c",
	"zNRBoPffRsnRB3bdMDtLcVkrCas/yxRv9gHFkrB+g6LOzt2Rgj0yYVamf2td6anrRu3Y9dcqEY9A3yoF",
	"VuX7RXQp1LXH9tVNjQrN9LK3mGTcBuHbc5RBXHdOYOgO07XTN8bKgN1tXKXb7y7Mb3kg73+X2C59zW/x",
	"PnrjexrWBPQx5dPly+Tq8QJ9wXWxbw4oydX4K5F47X5YxfeSq7udpYHJjTENm6G0BqFV3/38f/NtEwO6",
	"bL2TO91UgM38uTPRgFiwR7QZF1v4DDshigYRi7ZrajMR3dIrY/+AU9QoE3zEkPm+4e9eVowdE/s0y63c",
	"1IFNfZHkdR7sT5dvpetY7X7waLbFxLcONvUQzavOt5UB320/KR79Hm/um/kmV7h87K10b6RenQfjOfe1",
	"u22XIcP1WgDNljNSJvsu1rYRvSvvOia2Xygb9Os9FYUGxV8HmyWzxkFzCjZ7xaPVrPCeOQ783mOa75jC",
	"dMc5/Dq5X0dYem+UNTNFd3HvMIMNL01rYT57fidhVN076XpVgA3+n/X+kpC2t/bgQJOTSaEpfTqZY3Kl",
	"KAumTLjtRaWc2f7hUMp3uuqq/ICF8dnsVfb5SvawZnaOGuycBYeE4T4mx0DiNSiJDSdk5yxQ28eTajZ1",
	"NEzRJvPg4qH8de/3QZYua0/P79tYt4OKn5u1yVW/46MK0tfNax/dPZmpZERNVY8/mjLGC8kKO0dpeUKe",
	"5kRJq5WAXDCJI3jFKW4NQql8wpKrxpkGW6URMbC6MO6PXKub5QheCgFh7YIfiAGNlJle1D6swMgRvH1t",
	"/MlFv7tTBLwM9YYz+uFEBEdtTlvlpJISZ8zyhT/8P0NtRvBKpRwNUPYqHZCHZ/COvxrBPy/P3wOtwvLA",
	"g5IIKBcoVI4jeK/gmos0YTqFs/MPl6PqPNjJ4GOXPfDy4u1gOKjSRwbHo6PRER3oyVGynA9OBj+NjkY/",
	"DfwaJJk5nFdpKjPsCeb+gjYkslAzmsKvb9POl/KEIjX57OiokxnA8ly4CeVKHv7beLn2yt5dqmDogeSm",
	"c3i1SBI0FOZ4fo8deoOup7+3PsW3FKSTSnSUhowbOg9bOkAzJhzuY+onWGnImWYZWtRmCBNVyNTAgit/",
	"DYIZeSKePzwRIQ4x9Kd3hnW6iNL+gFNIXShkGgb14uEH9Y+PHy/A50L741U+FzoM4O8PP4CzkPXtppCO",
	"Tw6hoZPCFS5BOwjyyQiQ8ikZjNUdHcS+Mq/DURDCBJ6C40cQzjN/3jqkocMPbI4sBTWts4SM1cgyN9Ay",
	"SCf4FN1m9mMY5k8PP8zgW6R8EMCbBDE1YSv0Y3gEaXtzk3uk6LZNQ3jxOFuJPwJQnpojAAjdP8IsXKJe",
	"8AShPKoAadjG0kLTob1wZgEapzJGrqHb4eBwcXxIe4dZixi/cmP9/mJG8Clk7+SuPdoHZzg2/A8cOtEs",
	"tDR0gE/gjCVLf6ySrCsCYKVTdMrFCD7NUQJyUvFyNuPSZ7tVu2rzNOPQKYplRJr6rY7/WQXH/laDdgka",
	"UavYsxcjuPAdYVomyRHCGzqO4fSM+l4GcBzwa37o6JHAU2D1T67L/zv4qCwTB2eqkD46rq0nPmNe0QTr",
	"CoQjk1MurCd+BXgdg1/OQmptDSyU+sTdDHwuUC/LALUzL+n6hHHjjHglQHcZhJQ81dNm64R63dyOEYo1",
	"bfuU855BHg9385dt6oHmvL+bZy927ef3r1SBtspP81frrSbwrVWNhgMHA+gdFC35W1219BFkkU1QO+Dw",
	"C7ghm3OEjiCRWNeCEETWwLVbAH2rNCyg8tRxi/m7ZQLfRq0van1R64taX9T6HlzrGw5yZfou/qPcI6dK",
	"0bZyCqq6RMLfMEGH7Axwa2DKtbFAh8jquybe1qvt4H9wCRm7QuNkV3M0YNgUT8Oqo8ML4cBYdXEiXfrg",
	"V6lXJJ8f/X1VWWrcpbFGW/IYWSsHnWF9hX7ze+UyfqXS5b1Ncc/1ILdt95vVBd6uqCTH9zaCoIlEp0yE",
	"5wjPEZ4jPD8Vp8zhlzLOfbvJo1/C4YpDfxNOUtiuQslG/L6NO18Jlw8UR4iIFRErIlZErIhYT8KgLPP4",
	"2y36KzmgdC/SGnINsnTByssZq8YpVwS0E9Bw27BVgDcssWLp7cPgZww7ki80gjehiJJYRv2XwA2UKDaC",
	"X9U1ak+IZxo2uynj/Acqb8T+J7hUMqV+Q9pEuCDRdx6WjavpEw+8+7ONv/UJ0G+KwPdvsK4ebd3KXo3o",
	"H9E/on9E/4j+fwV79dCNl0v/hFO/x/kDCmQGvWMZ5kr4EKQba1oILFdMdbkz5c/phrj0uIdDp9HwjdAX",
	"oS9CX4S+CH2PD3313Y1rMuq8pIUtRqjZ0L+JY/iiumI/mLeNq/CcVSuYsSFAipWh7ExqqqRkeG0tZzMc",
	"QblFl0atrwfPj49G8HMhBN3Ob/gf/qaXvLDebvYrZNTnT36z2JCm9uC4uib7i2jvz/w6Gu56JWF/F+U9",
	"1X05bEe9nbCbkF125L4/aLLZnWduL/z9rVFliCpDVBmiyhBVhierMhx+8Vi9Ptr7M9pkTs7u6rm9SkDD",
	"k0b1VbEB1XV5IYI/ThfePhprnMInnFzShdswdbsrWdihltWFTKrbOftVgW+tCbQ7qu45WN/N46aBb3Eb",
	"RkTliMoRlSMqR1R+iqgcHqhdi8ZnPXe1m2CMM/gDtTqYMOMPdpsiw/SgXE199j1+Lpgoq+eiMA1LXxXS",
	"juClE/8DNT0oX85dNe1P2xfI0yv1/qWEjC3LhUSJ3uUYek+CB8Kjpf9nsfSb70FErSJqFVGriFpF1Cqe",
	"pFbRfICnV614K43jOqWfUXC8adRb1Bk9x4HSlpexrx4of1e/pvOnjIFvdYK6+5jX1iepIwpGFIwoGFEw",
	"ouA3O25MezewcglsOEecYpW4bYDuKDXG7YDAEq2MAdoKmExrZ/ZpY7lZvLG7HjJuXaD+rW3gP9155t7r",
	"57fKEH92b2Povl0aNYGoCURNIGoCURN4wvbw4Zf6oYZbrzEItLiqO7ym3y+qx5va6N39+oQi1K2HKB7O",
	"1H6+yrKIdxHvIt5FvIt49+3xzjTecVtzdPqMHtCDsiQ9Tz0tbKGRbt0yp2TNsoQuJqfQ7xVi7i/nSlju",
	"CqZV7U1Hk6s35b6vI8rtF+bi8eQIwhGEIwhHEI4gXIGwVfn6o8mXVuWgZLh6xMFf6mH2h/DwJnAPthSe",
	"TauV9Pb1j6fV/Sbl+WUqM4JLNkWwim7EXNKyVIV1A8/z6mEb1P5WzVWXtFX593iXSPMh1QjTEaYjTEeY",
	"jjAdYbqE6evmI3ybjWWH1FVxMOWjazDBqdL+s7+3Wirpj0lXseeP82YFoZIrA1xrXKiETehysVDVoNx4",
	"01f9ZuD3BdM9b9lFtI5oHdE6onVE678qWmcqRbH54bB3vkhvhnL56eHzhKmrmB8csSRiScSSiCVPEUvC",
	"u3Ob0eSiLNSHJ42PD48oobOIKRFTIqZETImY8id64q7cu/uflqu/Ptxbb6GPb/TaW4VdEasiVkWsilgV",
	"serp2D+HX+oXuLc4AwGsfLHbv4MvBGWlVC96+1e/3adkziyEa4NG8KE+/gjXcy4QmFxWxbUbZtmG0mAs",
	"F6LKVKGVOWcLhGTORapRApeg/GP+gQwfUiuHlnKNCd1XxA2tZY2ZWvTdMRzOblQYfHcMrfVyfTxSEcEy",
	"gmUEywiW36tht+4J1HVGXevTk0GTo2jMRXyK+BTxKeLTX+op1NIgcmhD7fm7Rc1p9T9g06krEQ77BYtM",
	"SbFck3b4NNDtgR4Z3cdRGrE1YmvE1oitEVv/Oo7Sw4lmMpnj5vQRcjtaPPhcMMGnHFP4hVsoqwITGlm6",
	"BL+xckknBoRKmIBkjsmVKiy9jyLRXit9BVN6ioUbyFH7DXe0KTHlVTnE79kOrYiMmBkxM2JmxMyImU8A",
	"M6/X4+Jv+UyzlM6lZ4WwPBd4g42rVEdwyTI8mCsnBFpdG9RwrvmMS388/gelgU2MW1v+5x9PYar0hKcp",
	"uiG6n+rnSY5+GsElIlzjxPjms5Tutsm1sipR4hQSwV1j9ByZD0V+urwsJm7ME7KZ6c+Meyym1zsae/Uq",
	"AleUdPNCj31KzfeOUY8gnkEeQmzXzrkJ6yTCZITJCJMRJp88TN7e/n8AAAD///4+zw8D7wAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
